### ISSUE TITLE
Problem building Linux binary on Travis

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1202]
## Problem Definition

When trying to build v1.6.0 Travis failed to build the Linux binary due to some incosistency between the expected and the installed version of setuptools.

Link to failed build: https://travis-ci.org/github/rotki/rotki/jobs/711081205

```
44 INFO: Removing temporary files and cleaning cache in /home/travis/.cache/pyinstaller
Traceback (most recent call last):
  File "/home/travis/virtualenv/python3.7.1/bin/pyinstaller", line 11, in <module>
    sys.exit(run())
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/PyInstaller/__main__.py", line 111, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/PyInstaller/__main__.py", line 63, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 844, in main
    build(specfile, kw.get('distpath'), kw.get('workpath'), kw.get('clean_build'))
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/PyInstaller/building/build_main.py", line 791, in build
    exec(code, spec_namespace)
  File "rotkehlchen.spec", line 71, in <module>
    get_system_spec()['rotkehlchen'],
  File "/home/travis/build/rotki/rotki/rotkehlchen/utils/misc.py", line 320, in get_system_spec
    'rotkehlchen': pkg_resources.require('rotkehlchen')[0].version,
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pkg_resources/__init__.py", line 898, in require
    needed = self.resolve(parse_requirements(requirements))
  File "/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages/pkg_resources/__init__.py", line 789, in resolve
    raise VersionConflict(dist, req).with_context(dependent_req)
pkg_resources.ContextualVersionConflict: (setuptools 41.0.1 (/home/travis/virtualenv/python3.7.1/lib/python3.7/site-packages), Requirement.parse('setuptools==40.6.2'), {'rotkehlchen'})
/home/travis/build/rotki/rotki/.eggs/setuptools_scm-4.1.2-py3.7.egg/setuptools_scm/git.py:68: UserWarning: "/home/travis/build/rotki/rotki" is shallow and may cause errors
  warnings.warn('"{}" is shallow and may cause errors'.format(wd.path))
./package.sh: line 63
```

Building the binary locally in Linux works fine.

## Task

Figure out why this happened, fix it and make sure that Travis can build binaries for Linux again.

**Comment by LefterisJP** [comment]
This has been solved by a46c5db
