### ISSUE TITLE
OTC Trades Edit trade frontend test flaky

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1222]
## Problem Definition

The OTC Trades edit trade test seems to be failing flakily in the CI. Example run [here](https://github.com/rotki/rotki/pull/1221/checks?check_run_id=911722169)

Including the generated video here. Check the OTC trades video out of the zip.
[videos-Linux.zip](https://github.com/rotki/rotki/files/4977717/videos-Linux.zip)

Relevant output:

```
https://on.cypress.io/element-has-detached-from-dom
      at Object.cypressErr (http://localhost:8080/__cypress/runner/cypress_runner.js:86207:11)
      at Object.throwErr (http://localhost:8080/__cypress/runner/cypress_runner.js:86162:18)
      at Object.throwErrByPath (http://localhost:8080/__cypress/runner/cypress_runner.js:86194:17)
      at retry (http://localhost:8080/__cypress/runner/cypress_runner.js:76849:16)
      at onFailFn (http://localhost:8080/__cypress/runner/cypress_runner.js:65634:16)
      at tryCatcher (http://localhost:8080/__cypress/runner/cypress_runner.js:120203:23)
      at Promise._settlePromiseFromHandler (http://localhost:8080/__cypress/runner/cypress_runner.js:118139:31)
      at Promise._settlePromise (http://localhost:8080/__cypress/runner/cypress_runner.js:118196:18)
      at Promise._settlePromise0 (http://localhost:8080/__cypress/runner/cypress_runner.js:118241:10)
      at Promise._settlePromises (http://localhost:8080/__cypress/runner/cypress_runner.js:118316:18)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueue (http://localhost:8080/__cypress/runner/cypress_runner.js:114928:16)
      at Async../node_modules/bluebird/js/release/async.js.Async._drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:114938:10)
      at Async.drainQueues (http://localhost:8080/__cypress/runner/cypress_runner.js:114812:14)

```

and later

```
(node:8900) Warning: a promise was created in a handler at internal/timers.js:439:21 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.cast (/home/runner/.cache/Cypress/3.8.3/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:225:13)
(node:8900) Warning: a promise was created in a handler at internal/timers.js:439:21 but was not returned from it, see http://goo.gl/rRqMUw
    at Function.Promise.cast (/home/runner/.cache/Cypress/3.8.3/Cypress/resources/app/packages/server/node_modules/bluebird/js/release/promise.js:225:13)
 ERROR  Error: Command failed: /home/runner/work/rotki/rotki/frontend/app/node_modules/cypress/bin/cypress run --config baseUrl=http://localhost:8080/ --headless
Error: Command failed: /home/runner/work/rotki/rotki/frontend/app/node_modules/cypress/bin/cypress run --config baseUrl=http://localhost:8080/ --headless
    at makeError (/home/runner/work/rotki/rotki/frontend/app/node_modules/execa/index.js:174:9)
    at /home/runner/work/rotki/rotki/frontend/app/node_modules/execa/index.js:278:16
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

## Task

Figure out why this happens and solve it

**Comment by kelsos** [comment]
I have not seen any flakiness on the otc edit tests in the last few months.
