### ISSUE TITLE
With gevent 1.3.5 attribute error at handling failed greenlets

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#124]
At the main loop with gevent 1.3.5 we got a problem when handling failed greenlets.

Trace below:

```
Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/rotkehlchen.py", line 329, in main_loop
    self.kraken.main_logic()
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/kraken.py", line 252, in main_logic
    req={'pair': ','.join(self.tradeable_pairs.keys())}
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/kraken.py", line 193, in query_public
    return retry_calls(5, 'kraken', method, self._query_public, method, req)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/utils.py", line 174, in retry_calls
    result = function(*args)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/kraken.py", line 190, in _query_public
    return self.check_and_get_response(response, method)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/kraken.py", line 162, in check_and_get_response
    response.status_code,
rotkehlchen.errors.RemoteError: Kraken API request https://api.kraken.com/0/public/Ticker for Ticker failed with HTTP status code: 502
2018-08-20T06:23:51Z <Greenlet "Greenlet-0" at 0x7fa0209d7048: <bound method Rotkehlchen.main_loop of <rotkehlchen.rotkehlchen.Rotkehlchen object at 0x7fa02951d0f0>>> failed with RemoteError                                                                                  

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 815, in gevent._greenlet.Greenlet._notify_links
  File "src/gevent/greenlet.py", line 110, in gevent._greenlet.FailureSpawnedLink.__call__
  File "src/gevent/greenlet.py", line 70, in gevent._greenlet.SpawnedLink.__call__
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/server.py", line 80, in handle_killed_greenlets
    greenlet.task_id,
AttributeError: 'gevent._greenlet.Greenlet' object has no attribute 'task_id'
2018-08-20T06:23:51Z (<bound method RotkehlchenServer.handle_killed_greenlets of <rotkehlchen.server.RotkehlchenServer object at 0x7fa02749fc88>>, <Greenlet "Greenlet-0" at 0x7fa0209d7048: <bound method Rotkehlchen.main_loop of <rotkehlchen.rotkehlchen.Rotkehlchen object at 0x7fa02951d0f0>>>) failed with AttributeError
```

**Comment by LefterisJP** [comment]
At the moment gevent is higher that 1.3.5 and this error is not ever seen: https://github.com/rotki/rotki/blob/7858aac05535c054f2cd629e86783e902668cf60/requirements.txt#L1
