### ISSUE TITLE
Handle binance clock skew error more gracefully

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1482]
## Abstract

Many users have seen this behavior from binance due to not completely synced local time clocks. And due to the way rotki handles it, each time we had to spend some time debugging to realize what is wrong. We should handle it more gracefully and show an actual warning to the user.

Definitely not this:

```
[16/09/2020 17:41:40 Mitteleuropäische Sommerzeit] rotkehlchen.exchanges.binance: Binance API request request_url=https://api.binance.com/api/v3/account?recvWindow=10000&timestamp=1600270900071&signature=[REDACTED]
[16/09/2020 17:41:40 Mitteleuropäische Sommerzeit] rotkehlchen.api.server: Exception on /api/1/exchanges [PUT]
Traceback (most recent call last):
  File "site-packages\flask\app.py", line 1949, in full_dispatch_request
  File "site-packages\flask\app.py", line 1935, in dispatch_request
  File "site-packages\flask_restful\__init__.py", line 458, in wrapper
  File "site-packages\flask\views.py", line 89, in view
  File "site-packages\flask_restful\__init__.py", line 573, in dispatch_request
  File "site-packages\webargs\core.py", line 366, in wrapper
  File "rotkehlchen\api\v1\resources.py", line 197, in put
  File "rotkehlchen\api\rest.py", line 125, in wrapper
  File "rotkehlchen\api\rest.py", line 393, in setup_exchange
  File "rotkehlchen\rotkehlchen.py", line 810, in setup_exchange
  File "rotkehlchen\exchanges\manager.py", line 94, in setup_exchange
  File "rotkehlchen\exchanges\binance.py", line 204, in validate_api_key
  File "rotkehlchen\exchanges\binance.py", line 295, in api_query_dict
  File "rotkehlchen\exchanges\binance.py", line 273, in api_query
rotkehlchen.errors.RemoteError: Binance API request https://api.binance.com/api/v3/account?recvWindow=10000&timestamp=1600270900071&signature=[SIGNATURE] for account failed with HTTP status code: 400, error code: -1021 and error message: Timestamp for this request was 1000ms ahead of the server's time.
[16/09/2020 17:41:40 Mitteleuropäische Sommerzeit] rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "PUT /api/1/exchanges HTTP/1.1" 500 216 0.373099
[16/09/2020 17:41:43 Mitteleuropäische Sommerzeit] rotkehlchen.api.rest: Request successful response={"result": {"warnings": [], "errors": []}, "message": ""}, status_code=200
```

![7qvJzcDY](https://user-images.githubusercontent.com/1658405/93365548-36454880-f84a-11ea-9fd5-48bfe685784a.jpg)

## Task

Do it.

**Comment by rudygt** [comment]
I took a shoot at this one, but I dont really know how to test it (I dont have a binance key)

https://github.com/rudygt/rotki

any suggestions how I can verify that this works would be appreciated, 

Thanks

**Comment by LefterisJP** [comment]
Hey @rudygt thanks a lot for putting the time to try and address it.

It's probably my bad but this is not what I really meant. I wanted to simply handle the error better too. A 500 Error should never happen and is always a bug on our implementation. And then warn the user to sync their system clock as it may have skewed.

You tried to handle the actual underlying error from what I see. Your approach is not bad. It does 1 extra API call at the beginning and then uses the offer in each API call. Can you open a PR for this though? It's hard to check it from your branch. I did have a look regardless and it does not work as it is right now since you put time in the `V3` endpoints which for us means the private ones, and it tries to authenticate it. Put it in the `V1` endpoints and then it works.

Can you open a PR and add a changelog entry too?

**Comment by rudygt** [comment]
Great, I did created the pull 

https://github.com/rotki/rotki/pull/1485

Thanks!
