### ISSUE TITLE
Error adding Binance API

### ISSUE THREAD

**Issue by pluja** [rotki/rotki#1496]
## Problem Definition

When setting up the Binance API, I keep getting the same error over and over again. I tried different APIs, different permisions, etc. But nothing seems to solve the problem. The error is the following:

`Error at setup of binance: Request failed with status code 500`

### System Description

Here add a detailed description of your system, e.g. output of the following script:

```
Linux user 5.8.6-1-MANJARO #1 SMP PREEMPT Thu Sep 3 13:19:36 UTC 2020 x86_64 GNU/Linux
Rotki version: 1.7.0
```

**Comment by LefterisJP** [comment]
Hey @pluja, this is strange. Can you please include the rotkehlchen.log of your system? You can find it under Help -> Logs directory.

It's quite possible the same issue as this: https://github.com/rotki/rotki/issues/1482

We handle it better in the upcoming v1.8.0 version, but if it is that it probably means your system's clock is out of sync and you can solve it by syncing the clock.

**Comment by pluja** [comment]
This seems to be the error part on the log:

```
[20/09/2020 22:24:24 CEST] rotkehlchen.exchanges.manager: Initializing exchanges
[20/09/2020 22:24:24 CEST] rotkehlchen.exchanges.exchange: Initialized binance exchange
[20/09/2020 22:24:24 CEST] rotkehlchen.exchanges.binance: Binance API request request_url=https://api.binance.com/api/v3/account?recvWindow=10000&timestamp=1600633464210&signature=0db4fe9000517f4094c525a0003a627ea4038b27dfa16c000a35a8604b0004bb
[20/09/2020 22:24:24 CEST] rotkehlchen.api.server: Exception on /api/1/exchanges [PUT]
Traceback (most recent call last):
  File "site-packages/flask/app.py", line 1949, in full_dispatch_request
  File "site-packages/flask/app.py", line 1935, in dispatch_request
  File "site-packages/flask_restful/__init__.py", line 458, in wrapper
  File "site-packages/flask/views.py", line 89, in view
  File "site-packages/flask_restful/__init__.py", line 573, in dispatch_request
  File "site-packages/webargs/core.py", line 366, in wrapper
  File "rotkehlchen/api/v1/resources.py", line 197, in put
  File "rotkehlchen/api/rest.py", line 125, in wrapper
  File "rotkehlchen/api/rest.py", line 393, in setup_exchange
  File "rotkehlchen/rotkehlchen.py", line 810, in setup_exchange
  File "rotkehlchen/exchanges/manager.py", line 94, in setup_exchange
  File "rotkehlchen/exchanges/binance.py", line 204, in validate_api_key
  File "rotkehlchen/exchanges/binance.py", line 295, in api_query_dict
  File "rotkehlchen/exchanges/binance.py", line 273, in api_query
rotkehlchen.errors.RemoteError: Binance API request https://api.binance.com/api/v3/account?recvWindow=10000&timestamp=1600633464210&signature=0db4fe9400017f4094c525a52f3a627ea0008b27dfa16c000a35a860400054bb for account failed with HTTP status code: 400, error code: -1021 and error message: Timestamp for this request is outside of the recvWindow.
[20/09/2020 22:24:24 CEST] rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "PUT /api/1/exchanges HTTP/1.1" 500 216 0.671140
[20/09/2020 22:24:25 CEST] rotkehlchen.api.rest: Request successful response={"result": {"warnings": [], "errors": []}, "message": ""}, status_code=200
[20/09/2020 22:24:25 CEST] rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "GET /api/1/messages/ HTTP/1.1" 200 245 0.001811
[20/09/2020 22:24:25 CEST] rotkehlchen.api.rest: Request successful response={"result": {"last_balance_save": 1600604329, "eth_node_connection": false, "history_process_start_ts": -1, "history_process_current_ts": -1}, "message": ""}, status_code=200
[20/09/2020 22:24:25 CEST] rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "GET /api/1/periodic/ HTTP/1.1" 200 345 0.002199
[20/09/2020 22:24:29 CEST] rotkehlchen.rotkehlchen: Main loop start
```

**Comment by LefterisJP** [comment]
Yeah it's exactly the same error. So the way so solve this is to sync your system's clock as it appears to be out of sync. For how to do that please google for instructions on your Operating system.

But you can also wait until the next version coming soon that will adjust the binance queries if the clock is not synced.

I suggest to fix the clock sync problem at its root though since it may affect other applications too.

**Comment by pluja** [comment]
Ok, thank you. I'll try.

**Comment by LefterisJP** [comment]
Hey @pluja is this issue fixed for you now?

**Comment by pluja** [comment]
Yes! Just checked that out, it's now working fine!
