### ISSUE TITLE
Rotki backend 500s out after a while

### ISSUE THREAD

**Issue by pereztechseattle** [rotki/rotki#1514]
## Problem Definition

Rotki seems to die about once every day or two and has to be restarted.  The backend returns 500 errors.

### System Description

MacOS

Obviously, this is a high severity issue as it renders the software unusable for bot purposes.

**Comment by LefterisJP** [comment]
Hey @pereztechseattle thanks for the issue!

So let's see why this happens.

To debug this we will need:

1. Rotki version
2. Macos version
3. The exact 500 error text
4. The rotkehlchen.log of the offending run (don't restart it as the log gets rewritten) to figure out why this is happening. You can find the log in: `~/Library/Application Support/rotki/data` for OSX

**Comment by LefterisJP** [comment]
> unusable for bot purposes.

Also I am curious what do you mean by this? What bot purpose would you use rotki for at this moment? Rotki can't trade for you yet. I understand if rotki was also a trading bot then this would be different.

**Comment by pereztechseattle** [comment]
I'll try and get the log next time.  There was no error message to go with the 500.

By unusable, I mean I'm using the Rotki backend to feed balance data to my bots who then decide if they want to trade or whatever.  If Rotki backend dies once a day, my bots cannot function.

**Comment by LefterisJP** [comment]
Aha I see, so you are using the backend alone? What version are you using

>  I'll try and get the log next time. There was no error message to go with the 500... or requests just hang.

Sure, please do that and we can see what the bug is. Generally 500 is always a bug. Should never happen (in theory).

> I mean I'm using the Rotki backend to feed balance data to my bots who then decide if they want to trade or whatever.

Oh interesting. That's a unique way of using Rotki. We will do anything we can to help you support your needs.

**Comment by pereztechseattle** [comment]
Got it!   Here's the relevant bit of the log:
```
02/10/2020 08:38:10 PDT] rotkehlchen.api.rest: Request successful response={"result": {"warnings": [], "errors": []}, "message": ""}, status_code=200
[02/10/2020 08:38:10 PDT] rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "GET /api/1/messages/ HTTP/1.1" 200 245 0.001398
[02/10/2020 08:38:10 PDT] rotkehlchen.api.rest: Request successful response={"result": {"last_balance_save": 1601579151, "eth_node_connection": false, "history_process_start_ts": -1, "history_process_current_ts": -1}, "message": ""}, status_code=200
[02/10/2020 08:38:10 PDT] rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "GET /api/1/periodic/ HTTP/1.1" 200 345 0.001401
[02/10/2020 08:38:15 PDT] rotkehlchen.api.rest: Request successful response={"result": {"last_balance_save": 1601579151, "eth_node_connection": false, "history_process_start_ts": -1, "history_process_current_ts": -1}, "message": ""}, status_code=200
[02/10/2020 08:38:15 PDT] rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "GET /api/1/periodic/ HTTP/1.1" 200 345 0.001484
[02/10/2020 08:38:15 PDT] rotkehlchen.api.rest: Request successful response={"result": {"warnings": [], "errors": []}, "message": ""}, status_code=200
[02/10/2020 08:38:15 PDT] rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "GET /api/1/messages/ HTTP/1.1" 200 245 0.001628
[02/10/2020 08:38:21 PDT] rotkehlchen.api.rest: Request successful response={"result": {"warnings": [], "errors": []}, "message": ""}, status_code=200
[02/10/2020 08:38:21 PDT] rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "GET /api/1/messages/ HTTP/1.1" 200 245 0.000760
[02/10/2020 08:38:21 PDT] rotkehlchen.api.rest: Request successful response={"result": {"last_balance_save": 1601579151, "eth_node_connection": false, "history_process_start_ts": -1, "history_process_current_ts": -1}, "message": ""}, status_code=200
[02/10/2020 08:38:21 PDT] rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "GET /api/1/periodic/ HTTP/1.1" 200 345 0.000900
[02/10/2020 08:38:22 PDT] rotkehlchen.rotkehlchen: Main loop start
[02/10/2020 08:38:22 PDT] rotkehlchen.rotkehlchen: Main loop end
[02/10/2020 08:38:22 PDT] rotkehlchen.rotkehlchen: Main loop start
[02/10/2020 08:38:22 PDT] rotkehlchen.rotkehlchen: Main loop end
[02/10/2020 08:38:23 PDT] web3.RequestManager: Making request. Method: eth_call
[02/10/2020 08:38:23 PDT] web3.providers.HTTPProvider: Making request HTTP. URI: https://api.mycryptoapi.com/eth, Method: eth_call
[02/10/2020 08:38:23 PDT] rotkehlchen.api.server: Exception on /api/1/blockchains/ETH/defi [GET]
Traceback (most recent call last):
  File "flask/app.py", line 1949, in full_dispatch_request
  File "flask/app.py", line 1935, in dispatch_request
  File "flask_restful/__init__.py", line 458, in wrapper
  File "flask/views.py", line 89, in view
  File "flask_restful/__init__.py", line 573, in dispatch_request
  File "webargs/core.py", line 366, in wrapper
  File "rotkehlchen/api/v1/resources.py", line 779, in get
  File "rotkehlchen/api/rest.py", line 125, in wrapper
  File "rotkehlchen/api/rest.py", line 1413, in get_defi_balances
  File "rotkehlchen/api/rest.py", line 1400, in _get_defi_balances
  File "rotkehlchen/chain/manager.py", line 780, in query_defi_balances
  File "rotkehlchen/chain/ethereum/zerion.py", line 111, in all_balances_for_account
  File "rotkehlchen/chain/ethereum/manager.py", line 534, in call_contract
  File "rotkehlchen/chain/ethereum/manager.py", line 303, in query
  File "rotkehlchen/chain/ethereum/manager.py", line 563, in _call_contract
  File "web3/contract.py", line 1449, in call_function
  File "web3/contract.py", line 964, in call
  File "web3/contract.py", line 1499, in call_contract_function
  File "eth_utils/functional.py", line 45, in inner
  File "web3/eth.py", line 434, in call
  File "web3/manager.py", line 149, in request_blocking
  File "web3/manager.py", line 128, in _make_request
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3/middleware/formatting.py", line 76, in apply_formatters
  File "web3/middleware/gas_price_strategy.py", line 34, in middleware
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3/middleware/formatting.py", line 74, in apply_formatters
  File "web3/middleware/attrdict.py", line 33, in middleware
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3/middleware/formatting.py", line 74, in apply_formatters
  File "web3/middleware/normalize_errors.py", line 25, in middleware
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3/middleware/formatting.py", line 74, in apply_formatters
  File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
  File "web3/middleware/formatting.py", line 74, in apply_formatters
  File "web3/middleware/exception_retry_request.py", line 105, in middleware
  File "web3/middleware/exception_retry_request.py", line 105, in middleware
  File "web3/providers/rpc.py", line 88, in make_request
  File "web3/_utils/request.py", line 34, in make_post_request
  File "requests/sessions.py", line 572, in post
  File "requests/sessions.py", line 524, in request
  File "requests/sessions.py", line 637, in send
  File "requests/adapters.py", line 416, in send
  File "requests/adapters.py", line 228, in cert_verify
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /var/folders/f0/z4blcrpd4njfc4671m2h0khr0000gn/T/_MEIiSZpvN/certifi/cacert.pem
[02/10/2020 08:38:23 PDT] rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "GET /api/1/blockchains/ETH/defi HTTP/1.1" 500 164 0.059821
[02/10/2020 08:38:25 PDT] rotkehlchen.rotkehlchen: query_balances called requested_save_data=False
[02/10/2020 08:38:25 PDT] rotkehlchen.exchanges.coinbasepro: Coinbase Pro API query request_method=GET, request_url=/accounts, options={}
[02/10/2020 08:38:25 PDT] rotkehlchen.api.server: Exception on /api/1/balances/ [GET]
Traceback (most recent call last):
  File "flask/app.py", line 1949, in full_dispatch_request
  File "flask/app.py", line 1935, in dispatch_request
  File "flask_restful/__init__.py", line 458, in wrapper
  File "flask/views.py", line 89, in view
  File "flask_restful/__init__.py", line 573, in dispatch_request
  File "webargs/core.py", line 366, in wrapper
  File "rotkehlchen/api/v1/resources.py", line 264, in get
  File "rotkehlchen/api/rest.py", line 125, in wrapper
  File "rotkehlchen/api/rest.py", line 348, in query_all_balances
  File "rotkehlchen/api/rest.py", line 330, in _query_all_balances
  File "rotkehlchen/rotkehlchen.py", line 612, in query_balances
  File "rotkehlchen/utils/interfaces.py", line 111, in wrapper
  File "rotkehlchen/utils/interfaces.py", line 70, in wrapper
  File "rotkehlchen/exchanges/coinbasepro.py", line 263, in query_balances
  File "rotkehlchen/exchanges/coinbasepro.py", line 206, in _api_query
  File "requests/sessions.py", line 524, in request
  File "requests/sessions.py", line 637, in send
  File "requests/adapters.py", line 416, in send
  File "requests/adapters.py", line 228, in cert_verify
```

**Comment by LefterisJP** [comment]
Thank you @pereztechseattle! This is useful.

There is also an unfinished exception at the end of the log. Could you add the whole thing? And this happens after leaving rotki running for approximately how long?

**Comment by LefterisJP** [comment]
Some more questions:

1. How do you run it? Do you only run the backend or do you run the entire packaged version?

2. How long after you start it, does this happen? 

We have to try and reproduce it and see how this happens

**Comment by pereztechseattle** [comment]
It happened again.  It doesn't appear to be near-daily like I thought.  Maybe more weekly.

Anyway, here's the end of the log.  Hope this helps.

```
06/10/2020 09:20:21 PDT] rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "GET /api/1/periodic/ HTTP/1.1" 200 345 0.001491
[06/10/2020 09:20:26 PDT] rotkehlchen.rotkehlchen: query_balances called requested_save_data=False
[06/10/2020 09:20:26 PDT] rotkehlchen.exchanges.coinbasepro: Coinbase Pro API query request_method=GET, request_url=/accounts, options={}
[06/10/2020 09:20:26 PDT] rotkehlchen.api.server: Exception on /api/1/balances/ [GET]
Traceback (most recent call last):
  File "flask/app.py", line 1949, in full_dispatch_request
  File "flask/app.py", line 1935, in dispatch_request
  File "flask_restful/__init__.py", line 458, in wrapper
  File "flask/views.py", line 89, in view
  File "flask_restful/__init__.py", line 573, in dispatch_request
  File "webargs/core.py", line 366, in wrapper
  File "rotkehlchen/api/v1/resources.py", line 264, in get
  File "rotkehlchen/api/rest.py", line 125, in wrapper
  File "rotkehlchen/api/rest.py", line 348, in query_all_balances
  File "rotkehlchen/api/rest.py", line 330, in _query_all_balances
  File "rotkehlchen/rotkehlchen.py", line 612, in query_balances
  File "rotkehlchen/utils/interfaces.py", line 111, in wrapper
  File "rotkehlchen/utils/interfaces.py", line 70, in wrapper
  File "rotkehlchen/exchanges/coinbasepro.py", line 263, in query_balances
  File "rotkehlchen/exchanges/coinbasepro.py", line 206, in _api_query
  File "requests/sessions.py", line 524, in request
  File "requests/sessions.py", line 637, in send
  File "requests/adapters.py", line 416, in send
  File "requests/adapters.py", line 228, in cert_verify
OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /var/folders/f0/z4blcrpd4njfc4671m2h0khr0000gn/T/_MEIO1b5M6/certifi/cacert.pem
[06/10/2020 09:20:26 PDT] rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "GET /api/1/balances/ HTTP/1.1" 500 164 0.017676
[06/10/2020 09:20:27 PDT] rotkehlchen.api.rest: Request successful response={"result": {"warnings": [], "errors": []}, "message": ""}, status_code=200
[06/10/2020 09:20:27 PDT] rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "GET /api/1/messages/ HTTP/1.1" 200 245 0.004084
[06/10/2020 09:20:27 PDT] rotkehlchen.api.rest: Request successful response={"result": {"last_balance_save": 1601930287, "eth_node_connection": false, "history_process_start_ts": -1, "history_process_current_ts": -1}, "message": ""}, status_code=200
[06/10/2020 09:20:27 PDT] rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "GET /api/1/periodic/ HTTP/1.1" 200 345 0.001144
[06/10/2020 09:20:27 PDT] rotkehlchen.rotkehlchen: Main loop start
[06/10/2020 09:20:27 PDT] rotkehlchen.rotkehlchen: Main loop end
[06/10/2020 09:20:27 PDT] rotkehlchen.rotkehlchen: Main loop start
[06/10/2020 09:20:27 PDT] rotkehlchen.rotkehlchen: Main loop end
[06/10/2020 09:20:31 PDT] rotkehlchen.api.rest: Request successful response={"result": {"last_balance_save": 1601930287, "eth_node_connection": false, "history_process_start_ts": -1, "history_process_current_ts": -1}, "message": ""}, status_code=200
[06/10/2020 09:20:31 PDT] rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "GET /api/1/periodic/ HTTP/1.1" 200 345 0.001433
[06/10/2020 09:20:31 PDT] rotkehlchen.api.rest: Request successful response={"result": {"warnings": [], "errors": []}, "message": ""}, status_code=200
[06/10/2020 09:20:31 PDT] rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "GET /api/1/messages/ HTTP/1.1" 200 245 0.001088
[06/10/2020 09:20:36 PDT] rotkehlchen.api.rest: Request successful response={"result": {"last_balance_save": 1601930287, "eth_node_connection": false, "history_process_start_ts": -1, "history_process_current_ts": -1}, "message": ""}, status_code=200
[06/10/2020 09:20:36 PDT] rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "GET /api/1/periodic/ HTTP/1.1" 200 345 0.002710
[06/10/2020 09:20:36 PDT] rotkehlchen.api.rest: Request successful response={"result": {"warnings": [], "errors": []}, "message": ""}, status_code=200
[06/10/2020 09:20:36 PDT] rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "GET /api/1/messages/ HTTP/1.1" 200 245 0.001378
[06/10/2020 09:20:41 PDT] rotkehlchen.api.rest: Request successful response={"result": {"last_balance_save": 1601930287, "eth_node_connection": false, "history_process_start_ts": -1, "history_process_current_ts": -1}, "message": ""}, status_code=200
[06/10/2020 09:20:41 PDT] rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "GET /api/1/periodic/ HTTP/1.1" 200 345 0.001418
[06/10/2020 09:20:41 PDT] rotkehlchen.api.rest: Request successful response={"result": {"warnings": [], "errors": []}, "message": ""}, status_code=200
[06/10/2020 09:20:41 PDT] rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "GET /api/1/messages/ HTTP/1.1" 200 245 0.002384
[06/10/2020 09:20:42 PDT] rotkehlchen.rotkehlchen: Main loop start
[06/10/2020 09:20:42 PDT] rotkehlchen.rotkehlchen: Main loop end
[06/10/2020 09:20:42 PDT] rotkehlchen.rotkehlchen: Main loop start
[06/10/2020 09:20:42 PDT] rotkehlchen.rotkehlchen: Main loop end
[06/10/2020 09:20:46 PDT] rotkehlchen.api.rest: Request successful response={"result": {"last_balance_save": 1601930287, "eth_node_connection": false, "history_process_start_ts": -1, "history_process_current_ts": -1}, "message": ""}, status_code=200
[06/10/2020 09:20:46 PDT] rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "GET /api/1/periodic/ HTTP/1.1" 200 345 0.001357
[06/10/2020 09:20:46 PDT] rotkehlchen.api.rest: Request successful response={"result": {"warnings": [], "errors": []}, "message": ""}, status_code=200
[06/10/2020 09:20:46 PDT] rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "GET /api/1/messages/ HTTP/1.1" 200 245 0.001149
[06/10/2020 09:20:51 PDT] rotkehlchen.api.rest: Request successful response={"result": {"last_balance_save": 1601930287, "eth_node_connection": false, "history_process_start_ts": -1, "history_process_current_ts": -1}, "message": ""}, status_code=200
[06/10/2020 09:20:51 PDT] rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "GET /api/1/periodic/ HTTP/1.1" 200 345 0.001282
[06/10/2020 09:20:51 PDT] rotkehlchen.api.rest: Request successful response={"result": {"warnings": [], "errors": []}, "message": ""}, status_code=200
[06/10/2020 09:20:51 PDT] rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "GET /api/1/messages/ HTTP/1.1" 200 245 0.001316
[06/10/2020 09:20:57 PDT] rotkehlchen.api.rest: Request successful response={"result": {"warnings": [], "errors": []}, "message": ""}, status_code=200
[06/10/2020 09:20:57 PDT] rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "GET /api/1/messages/ HTTP/1.1" 200 245 0.000839
[06/10/2020 09:20:57 PDT] rotkehlchen.api.rest: Request successful response={"result": {"last_balance_save": 1601930287, "eth_node_connection": false, "history_process_start_ts": -1, "history_process_current_ts": -1}, "message": ""}, status_code=200
[06/10/2020 09:20:57 PDT] rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "GET /api/1/periodic/ HTTP/1.1" 200 345 0.001265
[06/10/2020 09:20:57 PDT] rotkehlchen.rotkehlchen: Main loop start
[06/10/2020 09:20:57 PDT] rotkehlchen.rotkehlchen: Main loop end
[06/10/2020 09:20:57 PDT] rotkehlchen.rotkehlchen: Main loop start
[06/10/2020 09:20:57 PDT] rotkehlchen.rotkehlchen: Main loop end
[06/10/2020 09:21:01 PDT] rotkehlchen.api.rest: Request successful response={"result": {"warnings": [], "errors": []}, "message": ""}, status_code=200
[06/10/2020 09:21:01 PDT] rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "GET /api/1/messages/ HTTP/1.1" 200 245 0.001179
[06/10/2020 09:21:01 PDT] rotkehlchen.api.rest: Request successful response={"result": {"last_balance_save": 1601930287, "eth_node_connection": false, "history_process_start_ts": -1, "history_process_current_ts": -1}, "message": ""}, status_code=200
[06/10/2020 09:21:01 PDT] rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "GET /api/1/periodic/ HTTP/1.1" 200 345 0.001332
[06/10/2020 09:21:06 PDT] rotkehlchen.api.rest: Request successful response={"result": {"warnings": [], "errors": []}, "message": ""}, status_code=200
[06/10/2020 09:21:06 PDT] rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "GET /api/1/messages/ HTTP/1.1" 200 245 0.000776
[06/10/2020 09:21:06 PDT] rotkehlchen.api.rest: Request successful response={"result": {"last_balance_save": 1601930287, "eth_node_connection": false, "history_process_start_ts": -1, "history_process_current_ts": -1}, "message": ""}, status_code=200
[06/10/2020 09:21:06 PDT] rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "GET /api/1/periodic/ HTTP/1.1" 200 345 0.000896
[06/10/2020 09:21:10 PDT] rotkehlchen.api.rest: Request successful response={"result": {"warnings": [], "errors": []}, "message": ""}, status_code=200
[06/10/2020 09:21:10 PDT] rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "GET /api/1/messages/ HTTP/1.1" 200 245 0.001690
[06/10/2020 09:21:10 PDT] rotkehlchen.api.rest: Request successful response={"result": {"last_balance_save": 1601930287, "eth_node_connection": false, "history_process_start_ts": -1, "history_process_current_ts": -1}, "message": ""}, status_code=200
[06/10/2020 09:21:10 PDT] rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "GET /api/1/periodic/ HTTP/1.1" 200 345 0.001670
[06/10/2020 09:21:12 PDT] rotkehlchen.rotkehlchen: Main loop start
[06/10/2020 09:21:12 PDT] rotkehlchen.rotkehlchen: Main loop end
[06/10/2020 09:21:12 PDT] rotkehlchen.rotkehlchen: Main loop start
[06/10/2020 09:21:12 PDT] rotkehlchen.rotkehlchen: Main loop end

```

**Comment by pereztechseattle** [comment]
> 1. How do you run it? Do you only run the backend or do you run the entire packaged version?

I run the entire package.  I'm not aware of how to run just the backend - that might actually be preferable.  

I essentially use the UI "once" to configure everything and then my bots read from the REST API.

> 2. How long after you start it, does this happen?

Seems to be about a day to a week.

Thanks!

**Comment by pereztechseattle** [comment]
Just from what I can tell, it seems it doesn't recover from `OSError: Could not find a suitable TLS CA certificate bundle, invalid path: /var/folders/f0/z4blcrpd4njfc4671m2h0khr0000gn/T/_MEIO1b5M6/certifi/cacert.pem`

**Comment by kelsos** [comment]
At the moment there is no easy way to run the backend on it's own but we could provide standalone builds later. 
`_MEIO1b5M6` seems to be the format of the temp folder where the backend runs from. To me it seems that something deletes files in the folder. I will give it a try in a vm I have and I will get back to you. 

Is it also easy to provide the version of OSX you are on?

**Comment by kelsos** [comment]
![image](https://user-images.githubusercontent.com/2269732/95768747-20933980-0cb7-11eb-8244-fccf61394e33.png)

I think I just managed to verify my initial hypothesis. When you execute the dmg this structure is where the pyinstaller temp folder is extracted. Initially the file cacert.pem is properly extracted in that directory. If after a long usage the folder is not there this means that something deleted the folder. 

@pereztechseattle is it safe to assume that the application was minimized? I will let it run for a while to check what happens.

**Comment by kelsos** [comment]
@pereztechseattle this should not be an issue after v1.14.1. We changed how the packaging works for macos so now all the files of the backend should be permanently under `/Application/rotki.app/Content` instead. Since this was related to the previous packaging of the backend I am assuming that this will not be an issue anymore.
