### ISSUE TITLE
Pressing Tab during new account creation does not properly cycle through input fields

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1583]
## Problem Definition

When making a new account users who are used to cycling through input fields by pressing "Tab" will have a problem as it does not work. Check the gif :point_down: 
![Peek 2020-10-09 23-34](https://user-images.githubusercontent.com/1658405/95633714-8fd71680-0a88-11eb-915f-d0dd5ec195cd.gif)

I assume it's due to the "reveal password" button also getting selected during tab cycling.

## Task

Fix it ... probably by somehow ignoring the "Reveal password" button during the tab cycling

**Comment by FireLemons** [comment]
got stuck on the install because sqlcipher is really hard to install on linux

**Comment by LefterisJP** [comment]
@FireLemons hello. What does this have to do with the issue? sqlcipher is hard to install on windows but on most linux system it should be a breeze. https://rotki.readthedocs.io/en/latest/installation_guide.html#build-from-source

**Comment by piotrgredowski** [comment]
> got stuck on the install because sqlcipher is really hard to install on linux

> @FireLemons hello. What does this have to do with the issue? sqlcipher is hard to install on windows but on most linux system it should be a breeze. [rotki.readthedocs.io/en/latest/installation_guide.html#build-from-source](https://rotki.readthedocs.io/en/latest/installation_guide.html#build-from-source)

To be honest - I was trying to start with that issue because it should be quite easy to solve.
But had same problem :) I've run every step was mentioned in "Build from source" but after doing `npm run electron:serve` got below exception:
```
(node:21339) ExtensionLoadWarning: Warnings loading extension at /home/pg/.config/rotki/extensions/nhdogjmejiglipccpnnnanhbledajbpd: Unrecognized manifest key 'browser_action'. Unrecognized manifest key 'update_url'. Permission 'contextMenus' is unknown or URL pattern is malformed. Cannot load extension with file or directory name _metadata. Filenames starting with "_" are reserved for use by the system. 
2020-10-11T18:29:03.966Z: Determining if we are packaged by seeing if /home/pg/Coding/own/rotki/frontend/app/node_modules/electron/dist/resources/rotkehlchen_py_dist exists
2020-10-11T18:29:03.966Z: Starting non-packaged python subprocess: python -m rotkehlchen --api-port 4242 --api-cors http://localhost:8081 --logfile /home/pg/.config/rotki/logs/rotkehlchen.log
2020-10-11T18:29:03.970Z: The Python sub-process started on port: 4242 (PID: 21410)
2020-10-11T18:29:04.766Z: Traceback (most recent call last):
  File "/home/pg/.pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 193, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/pg/.pyenv/versions/3.8.2/lib/python3.8/runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "/home/pg/Coding/own/rotki/rotkehlchen/__main__.py", line 41, in <module>
    main()
  File "/home/pg/Coding/own/rotki/rotkehlchen/__main__.py", line 13, in main
    from rotkehlchen.server import RotkehlchenServer
  File "/home/pg/Coding/own/rotki/rotkehlchen/server.py", line 7, in <module>
    from rotkehlchen.api.server import APIServer, RestAPI
  File "/home/pg/Coding/own/rotki/rotkehlchen/api/server.py", line 16, in <module>
    from rotkehlchen.api.rest import RestAPI, api_response, wrap_in_fail_result
  File "/home/pg/Coding/own/rotki/rotkehlchen/api/rest.py", line 16, in <module>
    from rotkehlchen.api.v1.encoding import TradeSchema
  File "/home/pg/Coding/own/rotki/rotkehlchen/api/v1/encoding.py", line 16, in <module>
    from rotkehlchen.chain.ethereum.manager import EthereumManager
  File "/home/pg/Coding/own/rotki/rotkehlchen/chain/ethereum/manager.py", line 22, in <module>
    from rotkehlchen.chain.ethereum.transactions import EthTransactions
  File "/home/pg/Coding/own/rotki/rotkehlchen/chain/ethereum/transactions.py", line 5, in <module>
    from rotkehlchen.db.dbhandler import DBHandler
  File "/home/pg/Coding/own/rotki/rotkehlchen/db/dbhandler.py", line 12, in <module>
    from pysqlcipher3 import dbapi2 as sqlcipher
  File "/home/pg/Coding/own/rotki/rotki/lib/python3.8/site-packages/pysqlcipher3/dbapi2.py", line 33, in <module>
    from pysqlcipher3._sqlite3 import *
ImportError: libsqlcipher.so.0: cannot open shared object file: No such file or directory
2020-10-11T18:29:04.766Z: 
2020-10-11T18:29:04.766Z: The Python sub-process exited with signal: null (Code: 1)

```

**Comment by LefterisJP** [comment]
Hey guys thanks for your interest in Rotki. For general help with building and development please join the discord chat: https://discord.gg/aGCxHG7

@piotrgredowski your problem points to the same reason. You have either skipped or have not sucesfully completed the step to install sqlcipher. Me and the team can help with such questions in discord.

Let's keep the issues on topic.
