### ISSUE TITLE
Adding a bitrex account will return a 500 error when the system time is not synced

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#1785]
## Problem Definition

Adding a bitrex account when the system time is not properly synced results in the rotki API returning a 500 error.

## Logs

```python
Traceback (most recent call last):
  File "site-packages\flask\app.py", line 1949, in full_dispatch_request
  File "site-packages\flask\app.py", line 1935, in dispatch_request
  File "site-packages\flask_restful\__init__.py", line 458, in wrapper
  File "site-packages\flask\views.py", line 89, in view
  File "site-packages\flask_restful\__init__.py", line 573, in dispatch_request
  File "site-packages\webargs\core.py", line 366, in wrapper
  File "rotkehlchen\api\v1\resources.py", line 204, in put
  File "rotkehlchen\api\rest.py", line 130, in wrapper
  File "rotkehlchen\api\rest.py", line 398, in setup_exchange
  File "rotkehlchen\rotkehlchen.py", line 892, in setup_exchange
  File "rotkehlchen\exchanges\manager.py", line 94, in setup_exchange
  File "rotkehlchen\exchanges\bittrex.py", line 173, in validate_api_key
  File "rotkehlchen\exchanges\bittrex.py", line 230, in api_query
rotkehlchen.errors.RemoteError: Bittrex query responded with error status code: 401 and text: {"code":"INVALID_TIMESTAMP"}
```

**Comment by LefterisJP** [comment]
Should e fixed by https://github.com/rotki/rotki/pull/1807
