### ISSUE TITLE
Strange error with infura at test

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1816]
## Problem Definition

Seen at `rotkehlchen/tests/api/test_yearn_vaults.py::test_query_yearn_vault_history` here: 
https://pipelines.actions.githubusercontent.com/pzx0zrXmeq6QIlZyZm9oxyZTZyxPul0UQTasPXHu9fMGJXpoxp/_apis/pipelines/1/runs/1902/signedlogcontent/30?urlExpires=2020-11-26T23%3A06%3A06.6061865Z&urlSigningMethod=HMACV1&urlSignature=h9dKr60HKkbOXnX8bqDnqIO%2BBRZHhwC1xe7ipAkpmFg%3D

```
020-11-26T23:00:05.9532859Z [26/11/2020 22:51:59 UTC] DEBUG web3.providers.HTTPProvider: Making request HTTP. URI: https://mainnet.infura.io/v3/XXX, Method: eth_getLogs
2020-11-26T23:00:05.9534151Z [26/11/2020 22:51:59 UTC] DEBUG rotkehlchen.api.rest: Request successful response={"result": {"status": "pending", "outcome": null}, "message": "The task with id 0 is still pending"}, status_code=200
2020-11-26T23:00:05.9535759Z [26/11/2020 22:51:59 UTC] INFO rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "GET /api/1/tasks/0 HTTP/1.1" 200 237 0.000891
2020-11-26T23:00:05.9537881Z [26/11/2020 22:51:59 UTC] DEBUG web3.providers.HTTPProvider: Getting response HTTP. URI: https://mainnet.infura.io/v3/XXX, Method: eth_getLogs, Response: {'jsonrpc': '2.0', 'id': 21, 'result': None}
2020-11-26T23:00:05.9539387Z Traceback (most recent call last):
2020-11-26T23:00:05.9541412Z   File "src/gevent/greenlet.py", line 818, in gevent._greenlet.Greenlet.run
2020-11-26T23:00:05.9542538Z   File "/home/runner/work/rotki/rotki/rotkehlchen/api/rest.py", line 235, in _do_query_async
2020-11-26T23:00:05.9543483Z     result = getattr(self, command)(**kwargs)
2020-11-26T23:00:05.9544362Z   File "/home/runner/work/rotki/rotki/rotkehlchen/api/rest.py", line 1562, in _eth_module_query
2020-11-26T23:00:05.9545368Z     blockchain=SupportedBlockchain.ETHEREUM,
2020-11-26T23:00:05.9546425Z   File "/home/runner/work/rotki/rotki/rotkehlchen/utils/interfaces.py", line 115, in wrapper
2020-11-26T23:00:05.9547285Z     result = f(wrappingobj, *args, **kwargs)
2020-11-26T23:00:05.9548663Z   File "/home/runner/work/rotki/rotki/rotkehlchen/utils/interfaces.py", line 74, in wrapper
2020-11-26T23:00:05.9549519Z     result = f(wrappingobj, *args, **kwargs)
2020-11-26T23:00:05.9550392Z   File "/home/runner/work/rotki/rotki/rotkehlchen/chain/manager.py", line 379, in query_balances
2020-11-26T23:00:05.9551417Z     self.query_ethereum_balances(force_token_detection=force_token_detection)
2020-11-26T23:00:05.9552824Z   File "/home/runner/work/rotki/rotki/rotkehlchen/utils/interfaces.py", line 115, in wrapper
2020-11-26T23:00:05.9553668Z     result = f(wrappingobj, *args, **kwargs)
2020-11-26T23:00:05.9554548Z   File "/home/runner/work/rotki/rotki/rotkehlchen/utils/interfaces.py", line 74, in wrapper
2020-11-26T23:00:05.9555390Z     result = f(wrappingobj, *args, **kwargs)
2020-11-26T23:00:05.9556326Z   File "/home/runner/work/rotki/rotki/rotkehlchen/chain/manager.py", line 849, in query_ethereum_balances
2020-11-26T23:00:05.9557155Z     self._add_protocol_balances()
2020-11-26T23:00:05.9558043Z   File "/home/runner/work/rotki/rotki/rotkehlchen/chain/manager.py", line 885, in _add_protocol_balances
2020-11-26T23:00:05.9558890Z     self.get_staked_eth2_balances()
2020-11-26T23:00:05.9559785Z   File "/home/runner/work/rotki/rotki/rotkehlchen/chain/manager.py", line 987, in get_staked_eth2_balances
2020-11-26T23:00:05.9560623Z     database=self.database,
2020-11-26T23:00:05.9561539Z   File "/home/runner/work/rotki/rotki/rotkehlchen/chain/ethereum/eth2.py", line 202, in get_eth2_staked_amount
2020-11-26T23:00:05.9562289Z     to_ts=to_ts,
2020-11-26T23:00:05.9563146Z   File "/home/runner/work/rotki/rotki/rotkehlchen/chain/ethereum/eth2.py", line 114, in _get_eth2_staked_amount_onchain
2020-11-26T23:00:05.9564317Z     to_block='latest',
2020-11-26T23:00:05.9565089Z   File "/home/runner/work/rotki/rotki/rotkehlchen/chain/ethereum/contracts.py", line 52, in get_logs
2020-11-26T23:00:05.9565814Z     call_order=call_order,
2020-11-26T23:00:05.9566990Z   File "/home/runner/work/rotki/rotki/rotkehlchen/chain/ethereum/manager.py", line 673, in get_logs
2020-11-26T23:00:05.9567844Z     to_block=to_block,
2020-11-26T23:00:05.9568564Z   File "/home/runner/work/rotki/rotki/rotkehlchen/chain/ethereum/manager.py", line 343, in query
2020-11-26T23:00:05.9569311Z     result = method(web3, **kwargs)
2020-11-26T23:00:05.9570323Z   File "/home/runner/work/rotki/rotki/rotkehlchen/chain/ethereum/manager.py", line 714, in _get_logs
2020-11-26T23:00:05.9571160Z     argument_filters=argument_filters,
2020-11-26T23:00:05.9572107Z   File "/home/runner/work/rotki/rotki/rotkehlchen/chain/ethereum/manager.py", line 107, in _query_web3_get_logs
2020-11-26T23:00:05.9572915Z     raise e from None
2020-11-26T23:00:05.9573768Z   File "/home/runner/work/rotki/rotki/rotkehlchen/chain/ethereum/manager.py", line 101, in _query_web3_get_logs
2020-11-26T23:00:05.9574778Z     new_events_web3 = cast(List[Dict[str, Any]], web3.eth.getLogs(filter_args))
2020-11-26T23:00:05.9576156Z   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/web3/eth.py", line 503, in getLogs
2020-11-26T23:00:05.9577068Z     RPC.eth_getLogs, [filter_params],
2020-11-26T23:00:05.9578326Z   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/web3/manager.py", line 149, in request_blocking
2020-11-26T23:00:05.9579345Z     response = self._make_request(method, params)
2020-11-26T23:00:05.9580629Z   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/web3/manager.py", line 128, in _make_request
2020-11-26T23:00:05.9581577Z     return request_func(method, params)
2020-11-26T23:00:05.9582490Z   File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
2020-11-26T23:00:05.9584291Z   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
2020-11-26T23:00:05.9585328Z     response = make_request(method, formatted_params)
2020-11-26T23:00:05.9586904Z   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/web3/middleware/gas_price_strategy.py", line 34, in middleware
2020-11-26T23:00:05.9588297Z     return make_request(method, params)
2020-11-26T23:00:05.9589150Z   File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
2020-11-26T23:00:05.9590626Z   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
2020-11-26T23:00:05.9591645Z     response = make_request(method, formatted_params)
2020-11-26T23:00:05.9592914Z   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/web3/middleware/attrdict.py", line 33, in middleware
2020-11-26T23:00:05.9593866Z     response = make_request(method, params)
2020-11-26T23:00:05.9594723Z   File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
2020-11-26T23:00:05.9596194Z   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/web3/middleware/formatting.py", line 83, in apply_formatters
2020-11-26T23:00:05.9597143Z     formatter(response["result"]),
2020-11-26T23:00:05.9598061Z   File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
2020-11-26T23:00:05.9599394Z   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/eth_utils/applicators.py", line 110, in apply_one_of_formatters
2020-11-26T23:00:05.9600212Z     "The provided value did not satisfy any of the formatter conditions"
2020-11-26T23:00:05.9600861Z ValueError: The provided value did not satisfy any of the formatter conditions
2020-11-26T23:00:05.9603273Z 2020-11-26T22:51:59Z <Greenlet at 0x7f1d44d8e290: <bound method RestAPI._do_query_async of <rotkehlchen.api.rest.RestAPI object at 0x7f1d45af54d0>>('_eth_module_query', 0, module='yearn_vaults', method='get_history', query_specific_balances_before=['defi'], given_defi_balances=<function RestAPI.get_yearn_vaults_history.<locals, addresses=['0x7780E86699e941254c8f4D9b7eB08FF7e96BBE10', '0x, reset_db_data=False, from_timestamp=0, to_timestamp=1606431111)> failed with ValueError
2020-11-26T23:00:05.9604995Z 
2020-11-26T23:00:05.9606125Z [26/11/2020 22:51:59 UTC] ERROR rotkehlchen.api.rest: Greenlet for task 0 dies with exception: The provided value did not satisfy any of the formatter conditions.
2020-11-26T23:00:05.9607378Z Exception Name: <class 'ValueError'>
2020-11-26T23:00:05.9608151Z Exception Info: The provided value did not satisfy any of the formatter conditions
2020-11-26T23:00:05.9608791Z Traceback:
2020-11-26T23:00:05.9609542Z    File "src/gevent/greenlet.py", line 818, in gevent._greenlet.Greenlet.run
2020-11-26T23:00:05.9610523Z   File "/home/runner/work/rotki/rotki/rotkehlchen/api/rest.py", line 235, in _do_query_async
2020-11-26T23:00:05.9611274Z     result = getattr(self, command)(**kwargs)
2020-11-26T23:00:05.9612055Z   File "/home/runner/work/rotki/rotki/rotkehlchen/api/rest.py", line 1562, in _eth_module_query
2020-11-26T23:00:05.9612979Z     blockchain=SupportedBlockchain.ETHEREUM,
2020-11-26T23:00:05.9613964Z   File "/home/runner/work/rotki/rotki/rotkehlchen/utils/interfaces.py", line 115, in wrapper
2020-11-26T23:00:05.9614759Z     result = f(wrappingobj, *args, **kwargs)
2020-11-26T23:00:05.9615514Z   File "/home/runner/work/rotki/rotki/rotkehlchen/utils/interfaces.py", line 74, in wrapper
2020-11-26T23:00:05.9616209Z     result = f(wrappingobj, *args, **kwargs)
2020-11-26T23:00:05.9616922Z   File "/home/runner/work/rotki/rotki/rotkehlchen/chain/manager.py", line 379, in query_balances
2020-11-26T23:00:05.9617746Z     self.query_ethereum_balances(force_token_detection=force_token_detection)
2020-11-26T23:00:05.9618808Z   File "/home/runner/work/rotki/rotki/rotkehlchen/utils/interfaces.py", line 115, in wrapper
2020-11-26T23:00:05.9619682Z     result = f(wrappingobj, *args, **kwargs)
2020-11-26T23:00:05.9620499Z   File "/home/runner/work/rotki/rotki/rotkehlchen/utils/interfaces.py", line 74, in wrapper
2020-11-26T23:00:05.9621189Z     result = f(wrappingobj, *args, **kwargs)
2020-11-26T23:00:05.9621947Z   File "/home/runner/work/rotki/rotki/rotkehlchen/chain/manager.py", line 849, in query_ethereum_balances
2020-11-26T23:00:05.9622832Z     self._add_protocol_balances()
2020-11-26T23:00:05.9623458Z   File "/home/runner/work/rotki/rotki/rotkehlchen/chain/manager.py", line 885, in _add_protocol_balances
2020-11-26T23:00:05.9624055Z     self.get_staked_eth2_balances()
2020-11-26T23:00:05.9624680Z   File "/home/runner/work/rotki/rotki/rotkehlchen/chain/manager.py", line 987, in get_staked_eth2_balances
2020-11-26T23:00:05.9625276Z     database=self.database,
2020-11-26T23:00:05.9625914Z   File "/home/runner/work/rotki/rotki/rotkehlchen/chain/ethereum/eth2.py", line 202, in get_eth2_staked_amount
2020-11-26T23:00:05.9626448Z     to_ts=to_ts,
2020-11-26T23:00:05.9627036Z   File "/home/runner/work/rotki/rotki/rotkehlchen/chain/ethereum/eth2.py", line 114, in _get_eth2_staked_amount_onchain
2020-11-26T23:00:05.9627744Z     to_block='latest',
2020-11-26T23:00:05.9628326Z   File "/home/runner/work/rotki/rotki/rotkehlchen/chain/ethereum/contracts.py", line 52, in get_logs
2020-11-26T23:00:05.9628871Z     call_order=call_order,
2020-11-26T23:00:05.9629451Z   File "/home/runner/work/rotki/rotki/rotkehlchen/chain/ethereum/manager.py", line 673, in get_logs
2020-11-26T23:00:05.9629990Z     to_block=to_block,
2020-11-26T23:00:05.9630534Z   File "/home/runner/work/rotki/rotki/rotkehlchen/chain/ethereum/manager.py", line 343, in query
2020-11-26T23:00:05.9631099Z     result = method(web3, **kwargs)
2020-11-26T23:00:05.9631697Z   File "/home/runner/work/rotki/rotki/rotkehlchen/chain/ethereum/manager.py", line 714, in _get_logs
2020-11-26T23:00:05.9632294Z     argument_filters=argument_filters,
2020-11-26T23:00:05.9632944Z   File "/home/runner/work/rotki/rotki/rotkehlchen/chain/ethereum/manager.py", line 107, in _query_web3_get_logs
2020-11-26T23:00:05.9633513Z     raise e from None
2020-11-26T23:00:05.9634111Z   File "/home/runner/work/rotki/rotki/rotkehlchen/chain/ethereum/manager.py", line 101, in _query_web3_get_logs
2020-11-26T23:00:05.9634823Z     new_events_web3 = cast(List[Dict[str, Any]], web3.eth.getLogs(filter_args))
2020-11-26T23:00:05.9635863Z   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/web3/eth.py", line 503, in getLogs
2020-11-26T23:00:05.9636557Z     RPC.eth_getLogs, [filter_params],
2020-11-26T23:00:05.9637651Z   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/web3/manager.py", line 149, in request_blocking
2020-11-26T23:00:05.9638695Z     response = self._make_request(method, params)
2020-11-26T23:00:05.9639885Z   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/web3/manager.py", line 128, in _make_request
2020-11-26T23:00:05.9640768Z     return request_func(method, params)
2020-11-26T23:00:05.9641605Z   File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
2020-11-26T23:00:05.9643074Z   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
2020-11-26T23:00:05.9644108Z     response = make_request(method, formatted_params)
2020-11-26T23:00:05.9645423Z   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/web3/middleware/gas_price_strategy.py", line 34, in middleware
2020-11-26T23:00:05.9646378Z     return make_request(method, params)
2020-11-26T23:00:05.9647232Z   File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
2020-11-26T23:00:05.9648695Z   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/web3/middleware/formatting.py", line 74, in apply_formatters
2020-11-26T23:00:05.9649751Z     response = make_request(method, formatted_params)
2020-11-26T23:00:05.9650715Z   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/web3/middleware/attrdict.py", line 33, in middleware
2020-11-26T23:00:05.9651432Z     response = make_request(method, params)
2020-11-26T23:00:05.9652097Z   File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
2020-11-26T23:00:05.9653186Z   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/web3/middleware/formatting.py", line 83, in apply_formatters
2020-11-26T23:00:05.9653909Z     formatter(response["result"]),
2020-11-26T23:00:05.9655103Z   File "cytoolz/functoolz.pyx", line 250, in cytoolz.functoolz.curry.__call__
2020-11-26T23:00:05.9656686Z   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/eth_utils/applicators.py", line 110, in apply_one_of_formatters
2020-11-26T23:00:05.9657827Z     "The provided value did not satisfy any of the formatter conditions"
2020-11-26T23:00:05.9658343Z 
2020-11-26T23:00:05.9659784Z [26/11/2020 22:52:00 UTC] DEBUG rotkehlchen.api.rest: Request successful response={"result": {"status": "completed", "outcome": {"result": null, "message": "The backend query task died unexpectedly: The provided value did not satisfy any of the formatter conditions"}}, "message": ""}, status_code=200
2020-11-26T23:00:05.9661911Z [26/11/2020 22:52:00 UTC] INFO rotkehlchen.api.server.pywsgi: 127.0.0.1 - - "GET /api/1/tasks/0 HTTP/1.1" 200 339 0.004491
```

First time I see this, and also does not happen locally

## Task

Investigate what it may be and fix if possible.

**Comment by LefterisJP** [comment]
We have not seen this error again and since then we have also updated out ethereum dependencies. So I will close and possibly reopen if we happen to hit this again.
