### ISSUE TITLE
Unhandled exception at shutdown for premium users

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#1889]
## Problem Definition

This is not really something bad or a priority but it seems that sometimes something is not handled properly at shutdown (it does not always happen). It's not a user facing error since the app is already shutting down. The cleanup is just not happening properly

```
2020-12-10T10:54:41.181Z: Exiting the application
2020-12-10T10:54:43.600Z: Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 818, in gevent._greenlet.Greenlet.run
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/rotkehlchen.py", line 362, in main_loop
    self.premium_sync_manager.maybe_upload_data_to_server()
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/premium/sync.py", line 162, in maybe_upload_data_to_server
    b64_encoded_data, our_hash = self.data.compress_and_encrypt_db(self.password)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/data_handler.py", line 195, in compress_and_encrypt_db
    self.db.export_unencrypted(tempdb)
AttributeError: 'DataHandler' object has no attribute 'db'
2020-12-10T10:54:41Z <Greenlet at 0x7f2166ba6ef0: <bound method Rotkehlchen.main_loop of <rotkehlchen.rotkehlchen.Rotkehlchen object at 0x7f2166a71f10>>> failed with AttributeError
```

## Task

Figure out why and fix it

**Comment by LefterisJP** [comment]
This should actually not happen again anymore. Since the organization of the background tasks and the task manager the premium sync is one task in there. And all of them would be killed before the user logs out so this should not be seen anymore.

**Comment by LefterisJP** [comment]
> This should actually not happen again anymore. Since the organization of the background tasks and the task manager the premium sync is one task in there. And all of them would be killed before the user logs out so this should not be seen anymore.

Narrator: It happened again.
