### ISSUE TITLE
Query balances fails combining dicts (and more)

### ISSUE THREAD

**Issue by vnavascues** [rotki/rotki#2072]
User Rasputin using Rotki v1.11.0 reported:
- Force save the balances does not update a 2 days old snapshot (no errors are displayed).
- When Rotki is closed (and only then) the following error log appears in the terminal.

```
2021-01-11T12:38:04Z <Greenlet at 0x7f0ad86f34d0: <bound method RestAPI._do_query_async of <rotkehlchen.api.rest.RestAPI object at 0x7f0ada7b40d0>>('_query_all_balances', 9, save_data=True, ignore_cache=True)> failed with TypeError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 818, in gevent._greenlet.Greenlet.run
  File "rotkehlchen/api/rest.py", line 241, in _do_query_async
  File "rotkehlchen/api/rest.py", line 365, in _query_all_balances
  File "rotkehlchen/rotkehlchen.py", line 723, in query_balances
  File "rotkehlchen/utils/misc.py", line 157, in combine_stat_dicts
  File "rotkehlchen/utils/misc.py", line 140, in combine_dicts
  File "rotkehlchen/utils/misc.py", line 140, in <listcomp>
  File "rotkehlchen/utils/misc.py", line 146, in _add_entries
TypeError: 'Balance' object is not subscriptable
```
Investigate

**Comment by vnavascues** [comment]
Closed as it has been already fixed and merged in develop

**Comment by LefterisJP** [comment]
This a duplicate of https://github.com/rotki/rotki/issues/2040 and must have been fixed due to: 32b8d787f52340df295ae86974f77e074974eb01

The need to return a dict and not Balance in those functions is a remnant of old code which is rather ugly and we should at some point address. The issue for this is here: https://github.com/rotki/rotki/issues/2043

**Comment by LefterisJP** [comment]
Unfortunately the same exact issue is possible in Bitstamp. I will push a fix.

**Comment by vnavascues** [comment]
Thanks for addressing this
