### ISSUE TITLE
SubstrateInterface can raise TypeError

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2084]
## Problem Definition

As seen in this [test failure](https://github.com/rotki/rotki/pull/2030/checks?check_run_id=1697843338) it seems that the library we are using for substrate interface connections can under some circumstances raise a `TypeError`.

I think this is a bug in their implementation since from the stack trace it looks like the `response` is not checked against being `None`.

```
2021-01-13T21:16:33.0336089Z [13/01/2021 20:59:12 UTC] DEBUG rotkehlchen.chain.substrate.manager: Kusama querying last block url=https://kusama-rpc.polkadot.io/
2021-01-13T21:16:33.0337198Z Traceback (most recent call last):
2021-01-13T21:16:33.0343568Z   File "src/gevent/greenlet.py", line 818, in gevent._greenlet.Greenlet.run
2021-01-13T21:16:33.0344678Z   File "/home/runner/work/rotki/rotki/rotkehlchen/chain/substrate/manager.py", line 235, in _connect_node
2021-01-13T21:16:33.0345541Z     last_block = self._check_node_synchronization(node_interface)
2021-01-13T21:16:33.0346495Z   File "/home/runner/work/rotki/rotki/rotkehlchen/chain/substrate/manager.py", line 177, in _check_node_synchronization
2021-01-13T21:16:33.0347397Z     last_block = self._get_last_block(node_interface=node_interface)
2021-01-13T21:16:33.0348261Z   File "/home/runner/work/rotki/rotki/rotkehlchen/chain/substrate/manager.py", line 349, in _get_last_block
2021-01-13T21:16:33.0349024Z     block_hash=node_interface.get_chain_head(),
2021-01-13T21:16:33.0350332Z   File "/opt/hostedtoolcache/Python/3.7.9/x64/lib/python3.7/site-packages/substrateinterface/base.py", line 732, in get_block_number
2021-01-13T21:16:33.0351403Z     return int(response['result']['number'], 16)
2021-01-13T21:16:33.0352137Z TypeError: 'NoneType' object is not subscriptable
2021-01-13T21:16:33.0354258Z 2021-01-13T20:59:12Z <Greenlet at 0x7fab325ca4d0: <bound method SubstrateManager._connect_node of <rotkehlchen.chain.substrate.manager.SubstrateManager object at 0x7fab2c701d50>>(node=<KusamaNodeName.PARITY: 0>)> failed with TypeError
```

## Task

1. Handle this `TypeError` on our side and log a proper error and not fail with unhandled exception
2. Raise this issue with the library we use (https://github.com/polkascan/py-substrate-interface) as they either have a bug, or we are using them in the wrong way.

**Comment by vnavascues** [comment]
I did check how to request the last block
https://github.com/polkascan/py-substrate-interface/issues/62
