### ISSUE TITLE
Kusama account addition fails with AttributeError in v1.12.1

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2116]
## Problem Definition

Trying to add a Kusama account in v1.12.1 fails with `AttributeError`.

This happens only in packaged mode. This is why we missed it. If you load the exact same code by source it works.

It manifests like this:

```
[17/01/2021 10:12:30 CET] ERROR rotkehlchen.greenlets: Kusama manager connection to own node node died with exception: Invalid SubstrateInterface instantiation.
Exception Name: <class 'AttributeError'>
Exception Info: Invalid SubstrateInterface instantiation
Traceback:
  File "src/gevent/greenlet.py", line 818, in gevent._greenlet.Greenlet.run
  File "rotkehlchen/chain/substrate/manager.py", line 240, in _connect_node
  File "rotkehlchen/chain/substrate/manager.py", line 418, in _get_node_interface

[17/01/2021 10:12:30 CET] ERROR rotkehlchen.user_messages: Kusama manager connection to own node node died with exception: Invalid SubstrateInterface instantiation. Check the logs for more details
[17/01/2021 10:12:30 CET] ERROR rotkehlchen.greenlets: Kusama manager connection to parity node died with exception: Invalid SubstrateInterface instantiation.
Exception Name: <class 'AttributeError'>
Exception Info: Invalid SubstrateInterface instantiation
Traceback:
  File "src/gevent/greenlet.py", line 818, in gevent._greenlet.Greenlet.run
  File "rotkehlchen/chain/substrate/manager.py", line 240, in _connect_node
  File "rotkehlchen/chain/substrate/manager.py", line 418, in _get_node_interface
  ```

Can also see similar stack trace in the console where the binary was ran from:

```
2021-01-17T09:45:53.929Z: Starting packaged python subprocess: /tmp/lefteris/.mount_rotki-bd0Awo/resources/rotkehlchen_py_dist/rotkehlchen-1.12.1-linux --api-port 4242 --loglevel debug --api-cors app://* --logfile /home/lefteris/.config/rotki/logs/rotkehlchen.log
2021-01-17T09:45:53.935Z: The Python sub-process started on port: 4242 (PID: 19124)
^C2021-01-17T09:54:44.510Z: Exiting the application
2021-01-17T09:54:44.675Z: Traceback (most recent call last):
  File "rotkehlchen/chain/substrate/manager.py", line 408, in _get_node_interface
  File "site-packages/substrateinterface/base.py", line 450, in __init__
ValueError: Type registry preset 'kusama' not found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 818, in gevent._greenlet.Greenlet.run
  File "rotkehlchen/chain/substrate/manager.py", line 240, in _connect_node
  File "rotkehlchen/chain/substrate/manager.py", line 418, in _get_node_interface
AttributeError: Invalid SubstrateInterface instantiation
2021-01-17T09:47:30Z <Greenlet at 0x7fcc0ff06cb0: <bound method SubstrateManager._connect_node of <rotkehlchen.chain.substrate.manager.SubstrateManager object at 0x7fcc167b5f90>>(node=<KusamaNodeName.OWN: 0>, endpoint='http://localhost:9933')> failed with AttributeError

Traceback (most recent call last):
  File "rotkehlchen/chain/substrate/manager.py", line 408, in _get_node_interface
  File "site-packages/substrateinterface/base.py", line 450, in __init__
ValueError: Type registry preset 'kusama' not found

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 818, in gevent._greenlet.Greenlet.run
  File "rotkehlchen/chain/substrate/manager.py", line 240, in _connect_node
  File "rotkehlchen/chain/substrate/manager.py", line 418, in _get_node_interface
AttributeError: Invalid SubstrateInterface instantiation
2021-01-17T09:47:30Z <Greenlet at 0x7fcc0fe8d5f0: <bound method SubstrateManager._connect_node of <rotkehlchen.chain.substrate.manager.SubstrateManager object at 0x7fcc167b5f90>>(node=<KusamaNodeName.PARITY: 1>, endpoint='https://kusama-rpc.polkadot.io/')> failed with AttributeError
```

## Task

Figure out why it happens and fix it.

**Comment by LefterisJP** [comment]
Fixed by #2118
