### ISSUE TITLE
Error building py-sr25519-bindings from source on arm64/aarch64

### ISSUE THREAD

**Issue by tgerring** [rotki/rotki#2395]
## Problem Definition

This is a continuation of my efforts on #2280 to run Rotki on a Raspberry Pi 4/400. After pausing on the prior issue for more research, I decided to proceed with the backend build. Based on my research, it seems like Rust may be a dependency for the bindings? If so, I can add it to the pre-install build list documented on the other issue.

## Logs

```
Collecting py-sr25519-bindings>=0.1.2
  Downloading py_sr25519_bindings-0.1.2.tar.gz (12 kB)
  Installing build dependencies ... error
  ERROR: Command errored out with exit status 1:
   command: /home/ubuntu/.virtualenvs/rotki/bin/python /home/ubuntu/.virtualenvs/rotki/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-l76hips5/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- maturin
       cwd: None
  Complete output (57 lines):
  Collecting maturin
    Downloading maturin-0.9.0.tar.gz (85 kB)
    Installing build dependencies: started
    Installing build dependencies: finished with status 'done'
    Getting requirements to build wheel: started
    Getting requirements to build wheel: finished with status 'done'
      Preparing wheel metadata: started
      Preparing wheel metadata: finished with status 'done'
  Collecting toml~=0.10.0
    Using cached toml-0.10.2-py2.py3-none-any.whl (16 kB)
  Building wheels for collected packages: maturin
    Building wheel for maturin (PEP 517): started
    Building wheel for maturin (PEP 517): finished with status 'error'
    ERROR: Command errored out with exit status 1:
     command: /home/ubuntu/.virtualenvs/rotki/bin/python /home/ubuntu/.virtualenvs/rotki/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py build_wheel /tmp/tmpw4gtipiz
         cwd: /tmp/pip-install-5ud4a5ri/maturin_0a3cf22d1a1f4b07b90b8576a50cda15
    Complete output (36 lines):
    running bdist_wheel
    running build
    installing to build/bdist.linux-aarch64/wheel
    running install
    Traceback (most recent call last):
      File "/home/ubuntu/.virtualenvs/rotki/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 280, in <module>
        main()
      File "/home/ubuntu/.virtualenvs/rotki/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 263, in main
        json_out['return_val'] = hook(**hook_input['kwargs'])
      File "/home/ubuntu/.virtualenvs/rotki/lib/python3.8/site-packages/pip/_vendor/pep517/_in_process.py", line 204, in build_wheel
        return _build_backend().build_wheel(wheel_directory, config_settings,
      File "/tmp/pip-build-env-7aynt1nn/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 208, in build_wheel
        return self._build_with_temp_dir(['bdist_wheel'], '.whl',
      File "/tmp/pip-build-env-7aynt1nn/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 194, in _build_with_temp_dir
        self.run_setup()
      File "/tmp/pip-build-env-7aynt1nn/overlay/lib/python3.8/site-packages/setuptools/build_meta.py", line 142, in run_setup
        exec(compile(code, __file__, 'exec'), locals())
      File "setup.py", line 96, in <module>
        setup(
      File "/tmp/pip-build-env-7aynt1nn/overlay/lib/python3.8/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.8/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.8/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-build-env-7aynt1nn/overlay/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 228, in run
        self.run_command('install')
      File "/usr/lib/python3.8/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.8/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "setup.py", line 58, in run
        raise RuntimeError(
    RuntimeError: cargo not found in PATH. Please install rust (https://www.rust-lang.org/tools/install) and try again
    ----------------------------------------
    ERROR: Failed building wheel for maturin
  Failed to build maturin
  ERROR: Could not build wheels for maturin which use PEP 517 and cannot be installed directly
  ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/11/cf/4f51b3439856f06b851d21418c068a0faffcea4baf7e61e54ef07f319b07/py_sr25519_bindings-0.1.2.tar.gz#sha256=337a4dcd8c3091e4f233bb5e47f9a5e06aa6afdeb2474c962d4b5e86c5ddfc8f (from https://pypi.org/simple/py-sr25519-bindings/). Command errored out with exit status 1: /home/ubuntu/.virtualenvs/rotki/bin/python /home/ubuntu/.virtualenvs/rotki/lib/python3.8/site-packages/pip install --ignore-installed --no-user --prefix /tmp/pip-build-env-l76hips5/overlay --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- maturin Check the logs for full command output.
INFO: pip is looking at multiple versions of requests to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pysqlcipher3 to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pycryptodomex to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of pycryptodome to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of marshmallow to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of greenlet to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of gql to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of gevent to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of flask-restful to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of flask-cors to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of flask to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of coincurve to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of <Python from Requires-Python> to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of bech32 to determine which version is compatible with other requirements. This could take a while.
INFO: pip is looking at multiple versions of base58check to determine which version is compatible with other requirements. This could take a while.
ERROR: Could not find a version that satisfies the requirement py-sr25519-bindings>=0.1.2 (from substrate-interface)
ERROR: No matching distribution found for py-sr25519-bindings>=0.1.2
```

### System Description

Operating system: Linux ubuntu 5.8.0-1015-raspi #18-Ubuntu SMP PREEMPT Fri Feb 5 06:09:58 UTC 2021 aarch64 aarch64 aarch64 GNU/Linux
Rotki version: develop branch

**Comment by LefterisJP** [comment]
Hmm rust is not a normal dependency. But if the build system can not find a pre-built wheel for one of the dependencies in your system it will try to build from source. And this is what's happening with (https://pypi.org/project/maturin/) here. And that seems to require rust. But that is specific to the system/architecture you are trying.

Additionally I notice python 3.8 there. Rotki is not yet working with python 3.8. Try building with 3.7.

**Comment by kelsos** [comment]
Just to have it logged here this is the error on `armv7`

```
#18 227.2       Caused by: `cargo metadata` exited with an error:     Updating crates.io index
#18 227.2     warning: spurious network error (2 tries remaining): could not read directory '/root/.cargo/registry/index/github.com-1ecc6299db9ec823/.git//refs': Value too large for defined data type; class=Os (2)
#18 227.2     warning: spurious network error (1 tries remaining): could not read directory '/root/.cargo/registry/index/github.com-1ecc6299db9ec823/.git//refs': Value too large for defined data type; class=Os (2)
#18 227.2     error: failed to load source for a dependency on `hmac`
```

At least on docker, there are some workarounds for cross-compiling, where you use the host platform to do the download and the target platform to build.

**Comment by kelsos** [comment]
I am gonna close this issue since the issues regarding aarch64 should be solved already in develop.

With 1.21 we will also have the first release that will have an aarch64 docker image published.
