### ISSUE TITLE
Make sure cryptocompare does not query for custom tokens without symbol

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#2528]
## Problem Definition

This happens now when you have a custom token. Does not crash the app in any way, just kills a querying task. So it's nothing serious. But the querying task should not have existed in the first place.

```
2021-03-09T16:01:22.605Z: Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/externalapis/cryptocompare.py", line 995, in get_historical_data
    to_timestamp=Timestamp(0),
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/externalapis/cryptocompare.py", line 775, in _get_histohour_data_for_range
    to_timestamp=end_date,
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/externalapis/cryptocompare.py", line 511, in query_endpoint_histohour
    result = self._api_query(path=query_path)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/externalapis/cryptocompare.py", line 402, in _api_query
    raise RemoteError(error_message)
rotkehlchen.errors.RemoteError: Failed to query cryptocompare for: "https://min-api.cryptocompare.com/data/v2/histohour?fsym=_CETH_0X48FB253446873234F2FEBBF9BDEAA72D9D387F94&tsym=EUR&limit=2000&toTs=1615303777". Error: fsym param is invalid. (fsym length is higher than maxlength: 30)
```

## Task

Fix it by:

- [ ] Make sure no cryptocompare query task is made for custom tokens without a symbol
- [ ] Check what  is used if cryptocompare identifier is missing. Is it asset identifier, or asset symbol? Enforce symbol. If there is no symbol do nothing.

**Comment by yabirgb** [comment]
This can be closed then
