### ISSUE TITLE
Handle invalid ENS domains at rotki

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#2875]
From discord chat windrush reported that adding `fl00_id.loopring.eth` raises a 500 eror on the APP. I could replicate this.
The logs say

```
[08/05/2021 19:15:41 CEST] ERROR rotkehlchen.api.server: Exception on /api/1/blockchains/ETH [PUT]
Traceback (most recent call last):
  File "rotkehlchen/api/v1/encoding.py", line 1364, in _transform_eth_address
  File "site-packages/eth_utils/address.py", line 110, in to_checksum_address
  File "site-packages/eth_utils/address.py", line 55, in to_normalized_address
  File "site-packages/eth_utils/conversions.py", line 160, in hexstr_if_str
ValueError: when sending a str, it must be a hex string. Got: 'fl00_id.loopring.eth'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/idna/core.py", line 336, in uts46_remap
IndexError

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "site-packages/ens/utils.py", line 115, in normalize_name
  File "site-packages/idna/core.py", line 341, in uts46_remap
idna.core.InvalidCodepoint: Codepoint U+005F not allowed at position 5 in 'fl00_id.loopring.eth'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "site-packages/flask/app.py", line 1949, in full_dispatch_request
  File "site-packages/flask/app.py", line 1935, in dispatch_request
  File "site-packages/flask_restful/__init__.py", line 468, in wrapper
  File "site-packages/flask/views.py", line 89, in view
  File "site-packages/flask_restful/__init__.py", line 583, in dispatch_request
  File "rotkehlchen/api/v1/parser.py", line 59, in wrapper
  File "rotkehlchen/api/v1/parser.py", line 98, in parse
  File "site-packages/marshmallow/schema.py", line 714, in load
  File "site-packages/marshmallow/schema.py", line 885, in _do_load
  File "site-packages/marshmallow/schema.py", line 1085, in _invoke_load_processors
  File "site-packages/marshmallow/schema.py", line 1216, in _invoke_processors
  File "rotkehlchen/api/v1/encoding.py", line 1458, in transform_data
  File "rotkehlchen/api/v1/encoding.py", line 1368, in _transform_eth_address
  File "rotkehlchen/chain/ethereum/manager.py", line 564, in ens_lookup
  File "rotkehlchen/chain/ethereum/manager.py", line 395, in query
  File "rotkehlchen/chain/ethereum/manager.py", line 608, in _ens_lookup
  File "site-packages/ens/utils.py", line 117, in normalize_name
ens.exceptions.InvalidName: fl00_id.loopring.eth is an invalid name, because Codepoint U+005F not allowed at position 5 in 'fl00_id.loopring.eth'
```

**Comment by LefterisJP** [comment]
Fixed by #2879
