### ISSUE TITLE
Unhandled exception in web3 contract call

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#3045]
## Problem Definition

Seen only once while using v1.17.1

```
Traceback (most recent call last):
  File "site-packages/web3/contract.py", line 1507, in call_contract_function
  File "site-packages/eth_abi/codec.py", line 181, in decode_abi
  File "site-packages/eth_abi/decoding.py", line 127, in __call__
  File "site-packages/eth_utils/functional.py", line 45, in inner
  File "site-packages/eth_abi/decoding.py", line 173, in decode
  File "site-packages/eth_abi/decoding.py", line 127, in __call__
  File "site-packages/eth_abi/decoding.py", line 142, in decode
  File "site-packages/eth_abi/decoding.py", line 127, in __call__
  File "site-packages/eth_abi/decoding.py", line 198, in decode
  File "site-packages/eth_abi/decoding.py", line 308, in read_data_from_stream
eth_abi.exceptions.InsufficientDataBytes: Tried to read 32 bytes.  Only got 0 bytes

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "rotkehlchen/api/rest.py", line 271, in _do_query_async
  File "rotkehlchen/api/rest.py", line 638, in _query_blockchain_balances
  File "rotkehlchen/utils/mixins/lockable.py", line 40, in wrapper
  File "rotkehlchen/utils/mixins/cacheable.py", line 73, in wrapper
  File "rotkehlchen/chain/manager.py", line 482, in query_balances
  File "rotkehlchen/utils/mixins/lockable.py", line 40, in wrapper
  File "rotkehlchen/utils/mixins/cacheable.py", line 73, in wrapper
  File "rotkehlchen/chain/manager.py", line 1062, in query_ethereum_balances
  File "rotkehlchen/chain/manager.py", line 1031, in query_defi_balances
  File "rotkehlchen/chain/ethereum/defi/chad.py", line 30, in query_defi_balances
  File "rotkehlchen/chain/ethereum/defi/zerionsdk.py", line 264, in all_balances_for_account
  File "rotkehlchen/chain/ethereum/defi/zerionsdk.py", line 251, in _query_chain_for_all_balances
  File "rotkehlchen/chain/ethereum/contracts.py", line 33, in call
  File "rotkehlchen/chain/ethereum/manager.py", line 755, in call_contract
  File "rotkehlchen/chain/ethereum/manager.py", line 397, in query
  File "rotkehlchen/chain/ethereum/manager.py", line 784, in _call_contract
  File "site-packages/web3/contract.py", line 1449, in call_function
  File "site-packages/web3/contract.py", line 964, in call
  File "site-packages/web3/contract.py", line 1528, in call_contract_function
web3.exceptions.BadFunctionCallOutput: Could not decode contract function call getProtocolBalances return data b'' for output_types ['((string,string,string,string,uint256),((address,string),(((address,string,string,uint8),uint256),((address,string,string,uint8),uint256)[])[])[])[]']
2021-06-04T07:35:57Z <Greenlet at 0x7fc2329ca950: <bound method RestAPI._do_query_async of <rotkehlchen.api.rest.RestAPI object at 0x7fc2338a4a10>>('_query_blockchain_balances', 6, blockchain=<SupportedBlockchain.ETHEREUM: 'ETH'>, ignore_cache=False)> failed with BadFunctionCallOutput
```

## Task

Figure out why this may happen and handle more gracefully

**Comment by LefterisJP** [comment]
Fixed by #3048
