### ISSUE TITLE
Asset update API returns 500 when called outside of a session

### ISSUE THREAD

**Issue by kelsos** [rotki/rotki#3204]
## Problem Definition

We originally intended for the asset update endpoints to not be tied to sessions. This changed due to limitations but the API still allows for calls without a session that result in a 500 error.

## Logs

```python
[16/07/2021 12:16:12 CEST] ERROR rotkehlchen.api.server: Exception on /api/1/assets/updates [POST]
Traceback (most recent call last):
  File "/home/kelsos/.virtualenvs/rotkehlchen/lib/python3.7/site-packages/flask/app.py", line 1499, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/kelsos/.virtualenvs/rotkehlchen/lib/python3.7/site-packages/flask/app.py", line 1485, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/home/kelsos/.virtualenvs/rotkehlchen/lib/python3.7/site-packages/flask_restful/__init__.py", line 467, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/kelsos/.virtualenvs/rotkehlchen/lib/python3.7/site-packages/flask/views.py", line 83, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/kelsos/.virtualenvs/rotkehlchen/lib/python3.7/site-packages/flask_restful/__init__.py", line 582, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/kelsos/.virtualenvs/rotkehlchen/lib/python3.7/site-packages/webargs/core.py", line 450, in wrapper
    return func(*args, **kwargs)
  File "/home/kelsos/development/github/rotkehlchenio/rotkehlchen/rotkehlchen/api/v1/resources.py", line 491, in post
    return self.rest_api.perform_assets_updates(async_query, up_to_version, conflicts)
  File "/home/kelsos/development/github/rotkehlchenio/rotkehlchen/rotkehlchen/api/rest.py", line 3075, in perform_assets_updates
    response = self._perform_assets_updates(up_to_version, conflicts)
  File "/home/kelsos/development/github/rotkehlchenio/rotkehlchen/rotkehlchen/api/rest.py", line 3050, in _perform_assets_updates
    cursor = self.rotkehlchen.data.db.conn.cursor()
AttributeError: 'DataHandler' object has no attribute 'db'
```

**Comment by kelsos** [comment]
Fixed by #3206
