### ISSUE TITLE
Coinbase deposits/withdrawals failing to fetch

### ISSUE THREAD

**Issue by DugganB** [rotki/rotki#3901]
Getting an error when trying to fetch deposits/withdrawals or generate a tax report using coinbase as an exchange.

Message is: `Failed query for all exchanges: Error: The backend query task died unexpectedly: 'NoneType' object has no attribute 'get'`

Here is the logs:

```
AttributeError: 'NoneType' object has no attribute 'get'
2022-01-02T20:41:06Z <Greenlet at 0x2815c54a948: <bound method RestAPI._do_query_async of <rotkehlchen.api.rest.RestAPI object at 0x0000028159FB2688>>('_get_asset_movements', 36, filter_query=AssetMovementsFilterQuery(and_op=True, filters=[DB, only_cache=False)> failed with AttributeError

Traceback (most recent call last):
  File "src\\gevent\\greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "rotkehlchen\api\rest.py", line 294, in _do_query_async
  File "rotkehlchen\api\rest.py", line 895, in _get_asset_movements
  File "rotkehlchen\history\events.py", line 296, in query_asset_movements
  File "rotkehlchen\history\events.py", line 262, in _query_services_for_asset_movements
  File "rotkehlchen\utils\mixins\lockable.py", line 46, in wrapper
  File "rotkehlchen\exchanges\exchange.py", line 387, in query_deposits_withdrawals
  File "rotkehlchen\exchanges\coinbase.py", line 718, in query_online_deposits_withdrawals
  File "rotkehlchen\exchanges\coinbase.py", line 644, in _deserialize_asset_movement
  File "rotkehlchen\exchanges\utils.py", line 42, in deserialize_asset_movement_address
  File "rotkehlchen\exchanges\utils.py", line 30, in get_key_if_has_val
AttributeError: 'NoneType' object has no attribute 'get'
2022-01-02T21:01:46Z <Greenlet at 0x2815c337828: <bound method RestAPI._do_query_async of <rotkehlchen.api.rest.RestAPI object at 0x0000028159FB2688>>('_get_asset_movements', 37, filter_query=AssetMovementsFilterQuery(and_op=True, filters=[DB, only_cache=False)> failed with AttributeError

Traceback (most recent call last):
  File "src\\gevent\\greenlet.py", line 906, in gevent._gevent_cgreenlet.Greenlet.run
  File "rotkehlchen\api\rest.py", line 294, in _do_query_async
  File "rotkehlchen\api\rest.py", line 895, in _get_asset_movements
  File "rotkehlchen\history\events.py", line 296, in query_asset_movements
  File "rotkehlchen\history\events.py", line 262, in _query_services_for_asset_movements
  File "rotkehlchen\utils\mixins\lockable.py", line 46, in wrapper
  File "rotkehlchen\exchanges\exchange.py", line 387, in query_deposits_withdrawals
  File "rotkehlchen\exchanges\coinbase.py", line 718, in query_online_deposits_withdrawals
  File "rotkehlchen\exchanges\coinbase.py", line 644, in _deserialize_asset_movement
```

**Comment by LefterisJP** [comment]
Hey DugganB this sounds like a bug! Can you join Discord and maybe send us a bigger part of the logs. This is not the entire stack trace.

**Comment by DugganB** [comment]
Am in the discord now. Posted some extra logs.

**Comment by LefterisJP** [comment]
This is done and will be part of next patch release.
