### ISSUE TITLE
Crypto.com operation error

### ISSUE THREAD

**Issue by yabirgb** [rotki/rotki#4010]
## Problem Definition

Some data in crypto.com importer causes a division error in the code. In the user case it was a amount of 0.0000003 ETH that
the CSV assigned 0 as EUR value

## Logs

```
[28/01/2022 01:22:58 GMT Standard Time] INFO rotkehlchen.api.server.pywsgi 127.0.0.1 - - "OPTIONS /api/1/import HTTP/1.1" 200 314 0.000000
[28/01/2022 01:22:58 GMT Standard Time] ERROR rotkehlchen.api.server Exception on /api/1/import [PUT]
Traceback (most recent call last):
  File "site-packages\flask\app.py", line 1516, in full_dispatch_request
  File "site-packages\flask\app.py", line 1502, in dispatch_request
  File "site-packages\flask_restful\__init__.py", line 467, in wrapper
  File "site-packages\flask\views.py", line 84, in view
  File "site-packages\flask_restful\__init__.py", line 582, in dispatch_request
  File "site-packages\webargs\core.py", line 450, in wrapper
  File "rotkehlchen\api\v1\resources.py", line 1223, in put
  File "rotkehlchen\api\rest.py", line 194, in wrapper
  File "rotkehlchen\api\rest.py", line 2083, in import_data
  File "rotkehlchen\data\importer.py", line 688, in import_cryptocom_csv
  File "rotkehlchen\data\importer.py", line 589, in _import_cryptocom_associated_entries
  File "rotkehlchen\fval.py", line 88, in __truediv__
decimal.InvalidOperation: [<class 'decimal.DivisionUndefined'>]

[28/01/2022 01:22:58 GMT Standard Time] INFO rotkehlchen.api.server.pywsgi 127.0.0.1 - - "PUT /api/1/import HTTP/1.1" 500 216 0.041305
```

### System Description
Operating system: 
Rotki version: 1.23

**Comment by LefterisJP** [comment]
Should be fixed by #4023
