### ISSUE TITLE
Race when shutting down and uploading to premium

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#450]
## Problem Definition

This is a minor bug caused by a race during shutdown. It can happen that during shutdown and while having premium and uploading data to the server the shutdown cleanup happens while the main loop tries to upload data to the server. 

The result is an irregular shutdown.

```
^CTraceback (most recent call last):
  File "src/gevent/greenlet.py", line 716, in gevent._greenlet.Greenlet.run
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/rotkehlchen.py", line 320, in main_loop
    self.premium_sync_manager.maybe_upload_data_to_server()
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/premium/sync.py", line 139, in maybe_upload_data_to_server
    b64_encoded_data, our_hash = self.data.compress_and_encrypt_db(self.password)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/data_handler.py", line 415, in compress_and_encrypt_db
    self.db.export_unencrypted(tempdb)
AttributeError: 'DataHandler' object has no attribute 'db'
2019-08-05T06:34:06Z <Greenlet "Greenlet-0" at 0x7f91543d2830: <bound method Rotkehlchen.main_loop of <rotkehlchen.rotkehlchen.Rotkehlchen object at 0x7f915a81b590>>> failed with AttributeError

Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 815, in gevent._greenlet.Greenlet._notify_links
  File "src/gevent/greenlet.py", line 110, in gevent._greenlet.FailureSpawnedLink.__call__
  File "src/gevent/greenlet.py", line 70, in gevent._greenlet.SpawnedLink.__call__
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/server.py", line 117, in handle_killed_greenlets
    greenlet.task_id,
AttributeError: 'gevent._greenlet.Greenlet' object has no attribute 'task_id'
2019-08-05T06:34:06Z (<bound method RotkehlchenServer.handle_killed_greenlets of <rotkehlchen.server.RotkehlchenServer object at 0x7f915a5cf990>>, <Greenlet "Greenlet-0" at 0x7f91543d2830: <bound method Rotkehlchen.main_loop of <rotkehlchen.rotkehlchen.Rotkehlchen object at 0x7f915a81b590>>>) failed with AttributeError
```

## Task

Fix this by having proper locks. Maybe add tests .. but probably hard to test.

**Comment by LefterisJP** [comment]
Another occurence of this in v1.11.0

```
2021-01-03T08:41:05.985Z: Exiting the application
^[[A^[[B2021-01-03T08:41:11.584Z: Traceback (most recent call last):
  File "src/gevent/greenlet.py", line 818, in gevent._greenlet.Greenlet.run
  File "rotkehlchen/rotkehlchen.py", line 363, in main_loop
  File "rotkehlchen/premium/sync.py", line 206, in maybe_upload_data_to_server
AttributeError: 'DataHandler' object has no attribute 'db'
2021-01-03T08:41:11Z <Greenlet at 0x7fe6e9220950: <bound method Rotkehlchen.main_loop of <rotkehlchen.rotkehlchen.Rotkehlchen object at 0x7fe6f09b7550>>> failed with AttributeError
```

**Comment by LefterisJP** [comment]
This seems like a duplicate of https://github.com/rotki/rotki/issues/1889#issuecomment-771115221 and should close for the same reason.
