### ISSUE TITLE
Unicode logging entries in Windows

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#5057]
## Problem Definition

While checking the logs of a Windows user I noticed the following repeating multiple times inside rotki-electron.log

```--- Logging error ---
Traceback (most recent call last):
  File "logging\__init__.py", line 1086, in emit
  File "encodings\cp1252.py", line 19, in encode
UnicodeEncodeError: 'charmap' codec can't encode character '\u2728' in position 101: character maps to <undefined>
Call stack:
  File "rotkehlchen\api\rest.py", line 298, in _do_query_async
  File "rotkehlchen\api\rest.py", line 664, in _query_blockchain_balances
  File "rotkehlchen\utils\mixins\lockable.py", line 46, in wrapper
  File "rotkehlchen\utils\mixins\cacheable.py", line 97, in wrapper
  File "rotkehlchen\chain\manager.py", line 616, in query_balances
  File "rotkehlchen\utils\mixins\lockable.py", line 46, in wrapper
  File "rotkehlchen\utils\mixins\cacheable.py", line 97, in wrapper
  File "rotkehlchen\chain\manager.py", line 1150, in query_ethereum_balances
  File "rotkehlchen\chain\manager.py", line 1083, in query_ethereum_tokens
  File "rotkehlchen\chain\evm\tokens.py", line 341, in query_tokens_for_addresses
  File "rotkehlchen\chain\evm\tokens.py", line 181, in _get_multicall_token_balances
  File "logging\__init__.py", line 1800, in debug
  File "logging\__init__.py", line 1844, in log
  File "logging\__init__.py", line 1512, in log
  File "logging\__init__.py", line 1589, in _log
  File "logging\__init__.py", line 1599, in handle
  File "logging\__init__.py", line 1661, in callHandlers
  File "logging\__init__.py", line 952, in handle
  File "logging\handlers.py", line 75, in emit
  File "logging\__init__.py", line 1187, in emit
  File "logging\__init__.py", line 1091, in emit
Message: 'Greenlet-4: Found \u2728(0x714a91578624d76A209E9aA4aF9a1F55d78f9190) token balance for 0x<redacted> and balance 6.434434324'
Arguments: ()
```

I suspect there may be an issue making unicode log entries to a windows file

## Task

Reproduce and fix

**Comment by LefterisJP** [comment]
I asked the user in whose logs I saw this to send me their default encoding by typing `[System.Text.Encoding]::Default` in powershell.

Their result was
```
IsSingleByte      : True
BodyName          : iso-8859-1
EncodingName      : Western European (Windows)
HeaderName        : Windows-1252
WebName           : Windows-1252
WindowsCodePage   : 1252
IsBrowserDisplay  : True
IsBrowserSave     : True
IsMailNewsDisplay : True
IsMailNewsSave    : True
EncoderFallback   : System.Text.InternalEncoderBestFitFallback
DecoderFallback   : System.Text.InternalDecoderBestFitFallback
IsReadOnly        : True
CodePage          : 1252
```
It seems to be suggested that sometimes in some windows installations default encoding is this cp1252 which can also be seen in the logs traceback.

So by doing this change and specifying utf-8 it should be enforced.

There is many many such instances of people having problems with unicode and this cp1252 encoding

**Comment by LefterisJP** [comment]
Should be closed by https://github.com/rotki/rotki/pull/5059
