### ISSUE TITLE
rotki failed to start

### ISSUE THREAD

**Issue by aslimacc** [rotki/rotki#5073]
## Problem Definition

I uninstall rotki from my mac approximately 1 year ago. and now I re-install it. when I launch it, I get Error in the first page: rotki failed to start with logs below. Seems the database structure changed. So I searched how to delete it and did not find.

fyi I installed it with brew --cask

## Logs

[rotki-core] [rotki-core] Failed to start rotkehlchen backend:
Traceback (most recent call last):
  File "rotkehlchen/globaldb/upgrades/manager.py", line 65, in maybe_upgrade_globaldb
  File "rotkehlchen/globaldb/upgrades/v2_v3.py", line 369, in migrate_to_v3
  File "rotkehlchen/globaldb/upgrades/v2_v3.py", line 316, in translate_binance_pairs
  File "rotkehlchen/db/drivers/gevent.py", line 89, in execute
sqlite3.OperationalError: no such table: binance_pairs

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "rotkehlchen/__main__.py", line 20, in main
  File "rotkehlchen/server.py", line 32, in __init__
  File "rotkehlchen/rotkehlchen.py", line 141, in __init__
  File "rotkehlchen/globaldb/handler.py", line 135, in __new__
  File "rotkehlchen/globaldb/handler.py", line 95, in _initialize_global_db_directory
  File "rotkehlchen/globaldb/handler.py", line 74, in initialize_globaldb
  File "rotkehlchen/globaldb/upgrades/manager.py", line 74, in maybe_upgrade_globaldb
ValueError: Failed at global DB upgrade from version 2 to 3: no such table: binance_pairs

### System Description

Operating system: macOS Ventura 13.0
Rotki version: 1.26.0

**Comment by LefterisJP** [comment]
Hey @aslimacc thank you very much. The easiest way for you to probably proceed would be to go to `~/Library/Application Support/rotki/data/global` and delete the `global.db` since if you have not used rotki for a year you can have it recreated.

And I guess your user DB is probably also too old so it would probably make sense to restart it.

Other than that your exception shows a potential error in the edge case of someone not using rotki for over a year which we will have to address.

**Comment by LefterisJP** [comment]
Also if you could send us your global DB that would really help. You can DM us in discord: https://discord.gg/aGCxHG7

(note that to join you would need to have DMs open to solve a captcha challenge)

**Comment by LefterisJP** [comment]
Shouldbe fixed by #5076
