### ISSUE TITLE
Flaky sqlite failure - Error binding parameter 0 - probably unsupported type

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#5432]
## Problem Definition

During initial blockchain balance query, the ETH query task just died and no ETH balances were shown. It was a shock for a bit but then I realized something was wrong by looking at the logs. Happened first time and has never been seen before.

Restarting,it all went well. The logs of what happened are below.

## Logs

```
[19/01/2023 00:17:48 CET] DEBUG rotkehlchen.api.server Greenlet-8: start rotki api GET /api/1/balances/blockchains/ETH view_args={'blockchain': 'ETH'}, query_string=b'async_query=true'
[19/01/2023 00:17:48 CET] DEBUG rotkehlchen.api.server Greenlet-8: end rotki api GET /api/1/balances/blockchains/ETH view_args={'blockchain': 'ETH'}, query_string=b'async_query=true', status_code=200, result={'result': {'task_id': 7}, 'message': ''}
[19/01/2023 00:17:48 CET] DEBUG rotkehlchen.api.rest Greenlet-24: Async task with task id 7 started
...
...
[19/01/2023 00:18:10 CET] DEBUG rotkehlchen.chain.ethereum.manager Greenlet-7: Querying ethereum chain for ETH balance eth_addresses=["redacted--was about 20 addresses"]
[19/01/2023 00:18:10 CET] DEBUG web3.RequestManager Making request. Method: eth_call
[19/01/2023 00:18:10 CET] DEBUG web3.RequestManager Making request. Method: eth_chainId
[19/01/2023 00:18:10 CET] DEBUG web3.providers.HTTPProvider Making request HTTP. URI: https://eth-mainnet.alchemyapi.io/v2/REDACTEDKEY, Method: eth_chainId
[19/01/2023 00:18:10 CET] ERROR rotkehlchen.api.rest Greenlet with id 140602543744272: Greenlet for task 7 dies with exception: Error binding parameter 0 - probably unsupported type..
Exception Name: <class 'pysqlcipher3.dbapi2.InterfaceError'>
Exception Info: Error binding parameter 0 - probably unsupported type.
Traceback:
   File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "rotkehlchen/api/rest.py", line 298, in _do_query_async
  File "rotkehlchen/api/rest.py", line 664, in _query_blockchain_balances
  File "rotkehlchen/utils/mixins/lockable.py", line 46, in wrapper
  File "rotkehlchen/utils/mixins/cacheable.py", line 97, in wrapper
  File "rotkehlchen/chain/manager.py", line 616, in query_balances
  File "rotkehlchen/utils/mixins/lockable.py", line 46, in wrapper
  File "rotkehlchen/utils/mixins/cacheable.py", line 97, in wrapper
  File "rotkehlchen/chain/manager.py", line 1150, in query_ethereum_balances
  File "rotkehlchen/chain/manager.py", line 1083, in query_ethereum_tokens
  File "rotkehlchen/chain/evm/tokens.py", line 330, in query_tokens_for_addresses
  File "rotkehlchen/db/dbhandler.py", line 1303, in get_tokens_for_address
  File "rotkehlchen/db/drivers/gevent.py", line 89, in execute
```

### System Description

Operating system: Lunux
Rotki version: v1.26.3

**Comment by LefterisJP** [comment]
Will close this as it happened only once in 1.26.3 and has not been seen since and code has changed a lot since then.

**Comment by LefterisJP** [comment]
This has been seen a few times in develop right now (almost 1.28.0).

Suspicions raised by Alexey are it may be related to mutating the `BlockchainAccount` eth list. But not confirmed.

**Comment by LefterisJP** [comment]
Running on a PR that has the first 2 commits as of today from #6071 showed the same error:

```
[14/05/2023 16:16:49 CEST] DEBUG rotkehlchen.tasks.manager Greenlet-4: At task scheduling. Current greenlets: 14 Max greenlets: 2. Will not schedule.
[14/05/2023 16:16:49 CEST] ERROR rotkehlchen.api.rest Greenlet with id 140502404829952: Greenlet for task 98 dies with exception: Error binding parameter 0 - probably unsupported type..
Exception Name: <class 'pysqlcipher3.dbapi2.InterfaceError'>
Exception Info: Error binding parameter 0 - probably unsupported type.
Traceback:
   File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/api/rest.py", line 362, in _do_query_async
    result = command(self, **kwargs)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/api/rest.py", line 674, in query_blockchain_balances
    balances = self.rotkehlchen.chains_aggregator.query_balances(
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/utils/mixins/lockable.py", line 46, in wrapper
    result = f(wrappingobj, *args, **kwargs)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/utils/mixins/cacheable.py", line 122, in wrapper
    result = f(wrappingobj, *args, **kwargs)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/chain/aggregator.py", line 455, in query_balances
    getattr(self, query_method)(ignore_cache=ignore_cache)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/utils/mixins/lockable.py", line 46, in wrapper
    result = f(wrappingobj, *args, **kwargs)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/utils/mixins/cacheable.py", line 122, in wrapper
    result = f(wrappingobj, *args, **kwargs)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/chain/aggregator.py", line 907, in query_eth_balances
    self.query_evm_chain_balances(chain=SupportedBlockchain.ETHEREUM)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/chain/aggregator.py", line 877, in query_evm_chain_balances
    self.query_evm_tokens(manager=manager, balances=chain_balances)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/chain/aggregator.py", line 815, in query_evm_tokens
    balance_result, token_usd_price = manager.tokens.query_tokens_for_addresses(
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/chain/evm/tokens.py", line 346, in query_tokens_for_addresses
    saved_list, _ = self.db.get_tokens_for_address(
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/db/dbhandler.py", line 1169, in get_tokens_for_address
    cursor.execute(
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/db/drivers/gevent.py", line 90, in execute
    self._cursor.execute(statement, *bindings)

[14/05/2023 16:16:49 CEST] DEBUG rotkehlchen.api.server Greenlet-22: start rotki api GET /api/1/tasks/89 view_args={'task_id': 89}, query_string=b''
```

**Comment by LefterisJP** [comment]
Okay so unfortunately the hypothesis of Alexey was completely wrong. And if you look at the code it was never possible. Anyway good to have done the immutability changes but here are logs of the bindings when the error happens.

Adding this log

```diff
modified   rotkehlchen/db/dbhandler.py
@@ -1166,6 +1166,7 @@ class DBHandler:
         """
         ignored_asset_ids = self.get_ignored_asset_ids(cursor)
         last_queried_ts = None
+        log.debug(f'--> BINDINGS: {(address, blockchain.to_chain_id().serialize_for_db(), EVM_ACCOUNTS_DETAILS_LAST_QUERIED_TS, EVM_ACCOUNTS_DETAILS_TOKENS)}')  # noqa: E501
         cursor.execute(
             'SELECT key, value FROM evm_accounts_details WHERE account=? AND chain_id=? AND (key=? OR key=?)',  # noqa: E501
             (address, blockchain.to_chain_id().serialize_for_db(), EVM_ACCOUNTS_DETAILS_LAST_QUERIED_TS, EVM_ACCOUNTS_DETAILS_TOKENS),  # noqa: E501
```

This is what appeared in the logs when the error occured again:

```
[14/05/2023 22:06:43 CEST] DEBUG rotkehlchen.db.dbhandler Greenlet-24: --> BINDINGS: ('0xaddy1', 1, 'last_queried_timestamp', 'tokens')
[14/05/2023 22:06:43 CEST] DEBUG rotkehlchen.db.dbhandler Greenlet-24: --> BINDINGS: ('0xaddy2', 1, 'last_queried_timestamp', 'tokens')
[14/05/2023 22:06:43 CEST] DEBUG rotkehlchen.db.dbhandler Greenlet-24: --> BINDINGS: ('0xaddy3', 1, 'last_queried_timestamp', 'tokens')
[14/05/2023 22:06:43 CEST] DEBUG rotkehlchen.db.dbhandler Greenlet-24: --> BINDINGS: ('0xaddy4', 1, 'last_queried_timestamp', 'tokens')
[14/05/2023 22:06:43 CEST] DEBUG rotkehlchen.db.dbhandler Greenlet-24: --> BINDINGS: ('0xaddy5', 1, 'last_queried_timestamp', 'tokens')
[14/05/2023 22:06:43 CEST] DEBUG rotkehlchen.db.dbhandler Greenlet-24: --> BINDINGS: ('0xaddy6', 1, 'last_queried_timestamp', 'tokens')
[14/05/2023 22:06:43 CEST] DEBUG rotkehlchen.db.dbhandler Greenlet-24: --> BINDINGS: ('0xaddy7', 1, 'last_queried_timestamp', 'tokens')
[14/05/2023 22:06:43 CEST] DEBUG web3.providers.HTTPProvider Getting response HTTP. URI: https://eth-mainnet.alchemyapi.io/v2/XXX, Method: eth_call, Response: {'jsonrpc': '2.0', 'id': 446, 'result': 'XXX'}
[14/05/2023 22:06:43 CEST] DEBUG web3.RequestManager Making request. Method: eth_call
[14/05/2023 22:06:43 CEST] DEBUG web3.providers.HTTPProvider Making request HTTP. URI: https://eth-mainnet.alchemyapi.io/v2/XXX, Method: eth_call
[14/05/2023 22:06:43 CEST] DEBUG rotkehlchen.db.dbhandler Greenlet-24: --> BINDINGS: ('0xaddy8', 1, 'last_queried_timestamp', 'tokens')
[14/05/2023 22:06:43 CEST] ERROR rotkehlchen.api.rest Greenlet with id 139870912437760: Greenlet for task 5 dies with exception: Error binding parameter 0 - probably unsupported type..
Exception Name: <class 'pysqlcipher3.dbapi2.InterfaceError'>
Exception Info: Error binding parameter 0 - probably unsupported type.
Traceback:
   File "src/gevent/greenlet.py", line 908, in gevent._gevent_cgreenlet.Greenlet.run
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/api/rest.py", line 362, in _do_query_async
    result = command(self, **kwargs)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/api/rest.py", line 488, in query_all_balances
    result = self.rotkehlchen.query_balances(
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/rotkehlchen.py", line 870, in query_balances
    blockchain_result = self.chains_aggregator.query_balances(
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/utils/mixins/lockable.py", line 46, in wrapper
    result = f(wrappingobj, *args, **kwargs)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/utils/mixins/cacheable.py", line 122, in wrapper
    result = f(wrappingobj, *args, **kwargs)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/chain/aggregator.py", line 461, in query_balances
    getattr(self, query_method)(ignore_cache=ignore_cache)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/utils/mixins/lockable.py", line 46, in wrapper
    result = f(wrappingobj, *args, **kwargs)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/utils/mixins/cacheable.py", line 122, in wrapper
    result = f(wrappingobj, *args, **kwargs)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/chain/aggregator.py", line 907, in query_eth_balances
    self.query_evm_chain_balances(chain=SupportedBlockchain.ETHEREUM)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/chain/aggregator.py", line 877, in query_evm_chain_balances
    self.query_evm_tokens(manager=manager, balances=chain_balances)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/chain/aggregator.py", line 815, in query_evm_tokens
    balance_result, token_usd_price = manager.tokens.query_tokens_for_addresses(
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/chain/evm/tokens.py", line 346, in query_tokens_for_addresses
    saved_list, _ = self.db.get_tokens_for_address(
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/db/dbhandler.py", line 1170, in get_tokens_for_address
    cursor.execute(
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/db/drivers/gevent.py", line 90, in execute
    self._cursor.execute(statement, *bindings)
```

Parameters at last call are as correct as every other call.

**Comment by LefterisJP** [comment]
All right so the issue has been reproduced in a test in our repo here: https://github.com/rotki/rotki/pull/6071

The error seems to be an sqlite driver implementation error that causes a wrong instance of
"Error binding parameter 0 - probably unsupported type" flakily. Happened once
in a blue moon for our users so was hard to reproduce.

Happens only if opening a parallel write context in the same connection from which
the read only get_tokens_for_address is done. Makes no sense. As a read context
should not be affected. Secondly why only at that location?

Our current fix in the code is to repeat the cursor.execute()
without any delay. It works splendid. Same solution the coveragepy people used:
https://github.com/nedbat/coveragepy/issues/1010

Hopefully we will be able to find a proper solution if this is indeed an sqlite bug.

**Comment by LefterisJP** [comment]
So unfortunately this happened again and in a different place.

This cursor execute statement: https://github.com/rotki/rotki/blob/b864f71c584ce29a29ceaf789519a5051a51b5c5/rotkehlchen/chain/ethereum/modules/nft/nfts.py#L174


failed very rarely with the same error:

```
[22/06/2023 20:06:39 CEST] ERROR rotkehlchen.api.server Error binding parameter 0 - probably unsupported type.
Traceback (most recent call last):
  File "/home/lefteris/.virtualenvs/rotkipy39/lib/python3.9/site-packages/flask/app.py", line 1484, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lefteris/.virtualenvs/rotkipy39/lib/python3.9/site-packages/flask/app.py", line 1469, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/lefteris/.virtualenvs/rotkipy39/lib/python3.9/site-packages/flask/views.py", line 109, in view
    return current_app.ensure_sync(self.dispatch_request)(**kwargs)
  File "/home/lefteris/.virtualenvs/rotkipy39/lib/python3.9/site-packages/flask/views.py", line 190, in dispatch_request
    return current_app.ensure_sync(meth)(**kwargs)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/api/v1/resources.py", line 311, in wrapper
    return f(*args, **kwargs)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/api/v1/parser.py", line 66, in wrapper
    return func(*args, **kwargs)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/api/v1/resources.py", line 2499, in get
    return self.rest_api.get_nfts_balances(
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/api/rest.py", line 295, in inner
    response = func(rest_api, **kwargs)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/api/rest.py", line 3233, in get_nfts_balances
    return self._eth_module_query(
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/api/rest.py", line 2308, in _eth_module_query
    result = getattr(module_obj, method)(**kwargs)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/chain/ethereum/modules/nft/nfts.py", line 176, in get_db_nft_balances
    cursor.execute(
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/db/drivers/gevent.py", line 90, in execute
    self._cursor.execute(statement, *bindings)
pysqlcipher3.dbapi2.InterfaceError: Error binding parameter 0 - probably unsupported type.
[22/06/2023 20:06:39 CEST] CRITICAL rotkehlchen.api.server Greenlet-0: Unhandled exception when processing endpoint request exc_info=True, exception=Error binding parameter 0 - probably unsupported type.
```

Unlike the previous place this happened I was not able to reproduce reliably in a test. So for now what I will do is keep the previous test which does reproduce the case this happens in case a fix is found.

Noting down where it happened the second time. But also move the "fix" to all cursor.execute() in case there is an interface error. As it can happen rarely in more places the fix needs to go deeper.

I hate myself for writing this and really need to find a way to address this.

**Comment by LefterisJP** [comment]
Root cause found, three and a half years later. This was never a rotki or sqlite bug, and the bindings were always correct. It was a pre-2016 pysqlite bug that `rotki-pysqlcipher3` (2022.8.1 through 2024.10.1, shipped in rotki 1.26 to 1.41) inherited from the
  rigglemania/pysqlcipher3 fork and never got the upstream fix for. CPython fixed it in August 2016 for 3.5.3+ as bpo-10513 (https://github.com/python/cpython/issues/54722). One of the reproducers attached to that issue is literally named `bug-binding_parameter_0.py`.    

  ### Mechanism

  All on one shared connection:

  1. A reader executes a parameterized `SELECT` and consumes it partially. The statement is busy in sqlite and the binding marks it `in_use`. With gevent, readers yielded between rows constantly.
  2. Another greenlet's `write_ctx` ends with `conn.commit()`. The old binding's `commit()` ran `pysqlite_do_all_statements(ACTION_RESET)`: `sqlite3_reset()` on every statement of the connection, and every `in_use` flag cleared.
  3. The reader keeps iterating. Its next step restarts the query from row zero with whatever bindings were last bound. That is silent: duplicate rows, or rows for the wrong parameter.
  4. Any cursor executes the same SQL text. The per-connection statement cache returns the same statement, and since `in_use` is zero it looks free. `sqlite3_bind_*()` on a running statement returns `SQLITE_MISUSE` ("bind on a busy prepared statement"), which old pysqlite
  reported as `Error binding parameter 0 - probably unsupported type`.
  5. The failed execute resets the statement on its error path, which is why the blind retry "worked". It also restarted the other cursor's query underneath it, which is how the 1.39.1 `IndexError` in `get_used_query_range` (9394f4925b) came out of the retry path.        

  This explains every observation here: only under a parallel write context, only for SQL executed repeatedly from several cursors (tokens per address, the concurrent nft balance queries, `used_query_ranges`), correct parameters, and a retry fixing it.

  ### Reproduction

  Reproduced deterministically with no concurrency at all, by compiling the shipped 2024.10.1 C sources against system sqlite for Python 3.11: a partially consumed cursor, a commit, one more fetch, then the exact error string on a second cursor executing the same SQL     
  text.

  ```
  python 3.11.2 module=oldrotki 2.6.0 sqlite_version=3.40.1 end_tx=commit
  A first row  : (0,)
  A after commit: [(1,), (0,)] <- should be (1,), (2,); a restart shows (0,), (1,)
  B execute     : InterfaceError: Error binding parameter 0 - probably unsupported type.
  B retry       : OK -> [(3,), (4,)]
  ```

  A randomized interleaving of four cursors and commits on that binding hit the bind error in 2445 of 3000 runs and returned rows for the wrong bound parameter in 342 runs, which is the silent corruption nobody ever saw. The same script is clean on CPython 3.9 and 3.11   
  stdlib `sqlite3`, `rotki-pysqlcipher3` 2026.8.3, `rotki-sqlite` 2026.7.2 and `pysqlite3-binary` 0.5.0.

  ### Why it "disappeared"

  It never did. Since June 2023 the retry in `DBCursor.execute` swallowed every occurrence with a DEBUG log. It only surfaced again in 1.39.1 because the retry path itself returned a corrupt row.

  ### Why it cannot happen now

  Three independent reasons:

  - `rotki-pysqlcipher3` 2026.8.3 and `rotki-sqlite` are CPython 3.14 code. `commit()`/`rollback()` do not touch other statements, and cursor sharing asks sqlite via `sqlite3_stmt_busy()` instead of trusting a flag.
  - Readers run on pooled connections and share no statement cache with the writer.
  - `statement_lock` serializes all C calls per connection, which also covers the modern multithreaded cache race python/cpython#118172.

  The retry hack and the reproduction test are removed in https://github.com/rotki/rotki/pull/13048
