### ISSUE TITLE
rotki failed to start after upgrade + reinstall

### ISSUE THREAD

**Issue by spaceblankey** [rotki/rotki#5634]
## Problem Definition

upgraded from version 3 to version 16, presented with "There is a problem with the backend." Uninstalled an

## Logs
[rotki-core] Failed to start rotkehlchen backend:
Traceback (most recent call last):
  File "rotkehlchen\globaldb\upgrades\manager.py", line 83, in maybe_upgrade_globaldb
  File "rotkehlchen\globaldb\upgrades\v3_v4.py", line 388, in migrate_to_v4
  File "rotkehlchen\globaldb\upgrades\v3_v4.py", line 359, in _upgrade_address_book_table
  File "rotkehlchen\db\drivers\gevent.py", line 89, in execute
sqlite3.OperationalError: no such table: address_book

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "rotkehlchen\__main__.py", line 17, in main
  File "rotkehlchen\server.py", line 32, in __init__
  File "rotkehlchen\rotkehlchen.py", line 146, in __init__
  File "rotkehlchen\globaldb\handler.py", line 228, in __new__
  File "rotkehlchen\globaldb\handler.py", line 181, in _initialize_global_db_directory
  File "rotkehlchen\globaldb\handler.py", line 149, in initialize_globaldb
  File "rotkehlchen\globaldb\upgrades\manager.py", line 92, in maybe_upgrade_globaldb
ValueError: Failed at global DB upgrade from version 3 to 4: no such table: address_book

[rotki-core] 

### System Description

Operating system: windows 10
Rotki version:1.27.0

**Comment by LefterisJP** [comment]
What version did you upgrade from? Which rotki version? Seemslike there was a problem with the global DB upgrade. If it's too old a version and you have never used it in years and don't care about any data it's best to just delete the data directory and restart.

**Comment by LefterisJP** [comment]
Without any further information from the user for over a week closing the issue.
