### ISSUE TITLE
Rotki vue.js packaged version does not open in OSX.

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#613]
## Problem Definition

The packaged application fails to open in OSX.

A Javascript error occured in the main process:

```
Uncaught Exception:
Error: Failed to get 'logs' path: setAppLogsPath() must be called first.
    at new k (/Applications/rotki.app/Contents/Resources/app.asar/background.js:1:164399)
    at Module.<anonymous> (/Applications/rotki.app/Contents/Resources/app.asar/background.js:1:168641)
    at r (/Applications/rotki.app/Contents/Resources/app.asar/background.js:1:110)
    at Object.<anonymous> (/Applications/rotki.app/Contents/Resources/app.asar/background.js:1:77674)
    at r (/Applications/rotki.app/Contents/Resources/app.asar/background.js:1:110)
    at /Applications/rotki.app/Contents/Resources/app.asar/background.js:1:902
    at Object.<anonymous> (/Applications/rotki.app/Contents/Resources/app.asar/background.js:1:912)
    at Module._compile (internal/modules/cjs/loader.js:786:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:798:10)
    at Module.load (internal/modules/cjs/loader.js:645:32)
```

## Task

Fix it and make the OSX packaged version with vue.js open and work properly.

**Comment by kelsos** [comment]
@LefterisJP I certainly need a way to check OSX

**Comment by LefterisJP** [comment]
Well I guess some kind of end to end tests running in OSX would have caught this. Dont worry I will fix it.

**Comment by LefterisJP** [comment]
By the way the error is really strange since the code looks like the code that was there before vue.js and the [documentation](https://electronjs.org/docs/all#appgetpathname) states:

> If app.getPath('logs') is called without called app.setAppLogsPath() being called first, a default log directory will be created equivalent to calling app.setAppLogsPath() without a path parameter.

**Comment by kelsos** [comment]
So the documentation is outdated? I saw your comment in the issue :)
