### ISSUE TITLE
unexpected "HeartbeatError: Lost remote after 30000ms" when I haven't provided any api key

### ISSUE THREAD

**Issue by lestephane** [rotki/rotki#615]
Rotki's README states that Rotki is a local application, and during signup (which i expect only creates a local user account), it is stated that API keys are optional. So I decided to test the claim. I run the app in a Vagrant VM with a firewall disallowing any outgoing connection. This is something I always do when trying a new application that I don't trust yet. 

The create new user flow fails with `HeartbeatError: Lost remote after 30000ms`.
The user seems to nevertheless be created fine locally, because creating a new user again
for that name complains that it already exists. Attempting to login as that user fails in the same
way as the user creation (spinning icon, then eventually `HeartbeatError: Lost remote after 30000ms`).

```text
➜  rotki-linux-x64-v1.0.7 cat /home/vagrant/.config/rotkehlchen.log 
06/01/2020 17:26:53 UTC -- INFO:rotkehlchen.rotkehlchen:Unlocking user user=user, create_new=True, sync_approval=unknown
06/01/2020 17:26:54 UTC -- DEBUG:rotkehlchen.premium.sync:can sync data from server -- start
06/01/2020 17:27:18 UTC -- CRITICAL:root:Traceback (most recent call last):
  File "rotkehlchen/server.py", line 533, in unlock_user
  File "rotkehlchen/rotkehlchen.py", line 147, in unlock_user
  File "rotkehlchen/usage_analytics.py", line 145, in maybe_submit_usage_analytics
  File "rotkehlchen/usage_analytics.py", line 131, in create_usage_analytics
  File "rotkehlchen/usage_analytics.py", line 117, in retrieve_location_data
  File "rotkehlchen/usage_analytics.py", line 86, in query_ipstack
  File "site-packages/requests/api.py", line 75, in get
  File "site-packages/requests/api.py", line 60, in request
  File "site-packages/requests/sessions.py", line 524, in request
  File "site-packages/requests/sessions.py", line 637, in send
  File "site-packages/requests/adapters.py", line 449, in send
  File "site-packages/urllib3/connectionpool.py", line 600, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 354, in _make_request
  File "http/client.py", line 1229, in request
  File "http/client.py", line 1275, in _send_request
  File "http/client.py", line 1224, in endheaders
  File "http/client.py", line 1016, in _send_output
  File "http/client.py", line 956, in send
  File "site-packages/urllib3/connection.py", line 181, in connect
  File "site-packages/urllib3/connection.py", line 159, in _new_conn
  File "site-packages/urllib3/util/connection.py", line 57, in create_connection
  File "site-packages/gevent/_socketcommon.py", line 218, in getaddrinfo
  File "site-packages/gevent/resolver/thread.py", line 67, in getaddrinfo
  File "site-packages/gevent/pool.py", line 159, in apply
  File "src/gevent/event.py", line 268, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 293, in gevent._event.AsyncResult.get
  File "src/gevent/_abstract_linkable.py", line 165, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 169, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
zerorpc.exceptions.LostRemote: Lost remote after 10s heartbeat

06/01/2020 17:30:00 UTC -- INFO:rotkehlchen.rotkehlchen:Unlocking user user=user, create_new=True, sync_approval=unknown
06/01/2020 17:30:12 UTC -- INFO:rotkehlchen.rotkehlchen:Unlocking user user=user, create_new=False, sync_approval=unknown
06/01/2020 17:30:12 UTC -- DEBUG:rotkehlchen.premium.sync:can sync data from server -- start
06/01/2020 17:30:37 UTC -- CRITICAL:root:Traceback (most recent call last):
  File "rotkehlchen/server.py", line 533, in unlock_user
  File "rotkehlchen/rotkehlchen.py", line 147, in unlock_user
  File "rotkehlchen/usage_analytics.py", line 145, in maybe_submit_usage_analytics
  File "rotkehlchen/usage_analytics.py", line 131, in create_usage_analytics
  File "rotkehlchen/usage_analytics.py", line 117, in retrieve_location_data
  File "rotkehlchen/usage_analytics.py", line 86, in query_ipstack
  File "site-packages/requests/api.py", line 75, in get
  File "site-packages/requests/api.py", line 60, in request
  File "site-packages/requests/sessions.py", line 524, in request
  File "site-packages/requests/sessions.py", line 637, in send
  File "site-packages/requests/adapters.py", line 449, in send
  File "site-packages/urllib3/connectionpool.py", line 600, in urlopen
  File "site-packages/urllib3/connectionpool.py", line 354, in _make_request
  File "http/client.py", line 1229, in request
  File "http/client.py", line 1275, in _send_request
  File "http/client.py", line 1224, in endheaders
  File "http/client.py", line 1016, in _send_output
  File "http/client.py", line 956, in send
  File "site-packages/urllib3/connection.py", line 181, in connect
  File "site-packages/urllib3/connection.py", line 159, in _new_conn
  File "site-packages/urllib3/util/connection.py", line 57, in create_connection
  File "site-packages/gevent/_socketcommon.py", line 218, in getaddrinfo
  File "site-packages/gevent/resolver/thread.py", line 67, in getaddrinfo
  File "site-packages/gevent/pool.py", line 159, in apply
  File "src/gevent/event.py", line 268, in gevent._event.AsyncResult.get
  File "src/gevent/event.py", line 293, in gevent._event.AsyncResult.get
  File "src/gevent/_abstract_linkable.py", line 165, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_abstract_linkable.py", line 169, in gevent.__abstract_linkable.AbstractLinkable._wait_core
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 61, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/_greenlet_primitives.py", line 65, in gevent.__greenlet_primitives.SwitchOutGreenletWithLoop.switch
  File "src/gevent/__greenlet_primitives.pxd", line 35, in gevent.__greenlet_primitives._greenlet_switch
zerorpc.exceptions.LostRemote: Lost remote after 10s heartbeat

```

Why is it trying to connect to rotkehlchen.premium.sync? I did not give api keys. I just want to create a user account, and look around in the app, all locally.

**Comment by LefterisJP** [comment]
Hello @lestephane thank you for the issue!

> So I decided to test the claim. I run the app in a Vagrant VM with a firewall disallowing any outgoing connection. This is something I always do when trying a new application that I don't trust yet.

I don't understand what the problem is. Of-course Rotki is a local application. Local application means that your data are saved in your local filesystem and are encrypted with your password but it does need to connect to the internet in order to do a number of things:

1. Get prices of assets
2. Contact exchanges
3. Connect to etherscan or a remote node in order to ask the ethereum blockchain
4. Connect to blockchain.info in order to query Bitcoin account information
5. Submit anonymous usage analytics
6. ... and so on and so forth.


From the stack trace it seems that it crashes at (5).

You can opt out of submitting anonymous usage analytics from the settings. We need the analytics in order to be able to have some idea about the number of our users exactly because Rotki is a local application and not a webapp.

And you don't need to take my word for everything I am telling you, you can read the code in [this repository](https://github.com/rotki/rotki/tree/master).

Specifically the usage analytics code is here:

https://github.com/rotki/rotki/blob/7991d254f60ee6db2764db7b12296a5b5a732e18/rotkehlchen/usage_analytics.py#L123-L155

**Comment by LefterisJP** [comment]
On the other hand @lestephane  the way the application reacted when not allowed to have any outgoing connections is not ideal.

This is something that we should improve and inform the user properly that this can not work. Thank you for pointing that out.

**Comment by lestephane** [comment]
I will enable the firewall rules for outgoing connection case by case, and only for the endpoints that I need to reach. This is especially true for an app that I did not build from source myself.

I cannot access the settings to disable the anonymous statistics. All the buttons are greyed out as long as one hasn't logged in. And I cannot login because of this problem, so I can't switch it off. Maybe prompt people whether they're OK with anonymous statistics using a checkbox in the account creation form. In the meantime, if you can tell me how to switch off the anonymous stats by modifying a config file, I'll be happy to report any further UX problem I have.

**Comment by LefterisJP** [comment]
Hey @lestephane 

> I will enable the firewall rules for outgoing connection case by case, and only for the endpoints that I need to reach.

Fair enough, that is your prerogative.

> This is especially true for an app that I did not build from source myself.

You can run the app from source and modify anything you want. It's not a closed source binary. Since it's python and node.js building is easy. Check [the docs](https://rotki.readthedocs.io/en/latest/installation_guide.html#build-from-source)

> I cannot access the settings to disable the anonymous statistics. All the buttons are greyed out as long as one hasn't logged in. And I cannot login because of this problem, so I can't switch it off.  Maybe prompt people whether they're OK with anonymous statistics using a checkbox in the account creation form

I understand your problem and your concern. But we are not not planning to make this setting opt-in though since trying to run an application that is local is already putting us at a huge disadvantage compared to all the SaaS competition of portfolio tracking applications. Getting some idea of how many active users we have and what they use is pertinent for us.

I can help you though by giving you a nice hack to deal with this since this seems important to you and I appreciate the need of total control of privacy ... this is also why we are making this application!

You can change the setting directly on your own by opening the DB manually.

Check [this](https://github.com/rotki/rotki/issues/587#issuecomment-569807986) comment in a different issue.

Essentially you need to get `sqlcipher` in your system. This is to open your DB manually. Once you got that the DB should be under `/home/.rotkehlchen/YOUR_USERNAME/rotkehlchen.db`.

In a terminal type: `sqlcipher ~/.rotkehlchen/USERNAME/rotkehlchen.db`

Replace `USERNAME` with your username and press `ENTER`.

This should give you a prompt like below:

```
SQLCipher version 3.28.0 2019-04-16 19:49:53
Enter ".help" for usage hints.
sqlite> 
```

Inside this prompt type:

`sqlite> PRAGMA key="PASSWORD";`

Replace `PASSWORD` with your password and press `ENTER`.

Now your database is unlocked for this session.
It's all `sqlite` queries now.

Type:

```
INSERT OR REPLACE INTO settings(name, value) VALUES("submit_usage_analytics", "False");
```

This way you can change any setting manually. To check your settings do : `SELECT * from settings;`

> I'll be happy to report any further UX problem I have.

That would be great.

**Comment by LefterisJP** [comment]
All the questions have been answered and there has been no response for some time so I am closing this issue.

If there are more questions or problems don't hesitate to open another issue.
