### ISSUE TITLE
rotki failed to start

### ISSUE THREAD

**Issue by perjez** [rotki/rotki#6236]
### System Description
[rotki-core] Failed to start rotki backend:
Traceback (most recent call last):
  File "rotkehlchen\globaldb\upgrades\manager.py", line 85, in maybe_upgrade_globaldb
  File "rotkehlchen\globaldb\upgrades\v3_v4.py", line 388, in migrate_to_v4
  File "rotkehlchen\globaldb\upgrades\v3_v4.py", line 359, in _upgrade_address_book_table
  File "rotkehlchen\db\drivers\gevent.py", line 89, in execute
sqlite3.OperationalError: no such table: address_book

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "rotkehlchen\__main__.py", line 17, in main
  File "rotkehlchen\server.py", line 32, in __init__
  File "rotkehlchen\rotkehlchen.py", line 150, in __init__
  File "rotkehlchen\globaldb\handler.py", line 212, in __new__
  File "rotkehlchen\globaldb\handler.py", line 178, in _initialize_global_db_directory
  File "rotkehlchen\globaldb\handler.py", line 143, in initialize_globaldb
  File "rotkehlchen\globaldb\upgrades\manager.py", line 94, in maybe_upgrade_globaldb
ValueError: Failed at global DB upgrade from version 3 to 4: no such table: address_book

[rotki-core] 

Operating system: 
Rotki version:

**Comment by yabirgb** [comment]
Hello @perjez ! We had this issue in the previous release when updating your data. A similar report is https://github.com/rotki/rotki/issues/5073 but should be fixes if you opened your db with 1.28. What version are you using?

**Comment by perjez** [comment]
Hi, thank you for quick reply! I´m using App Version: 
1.27.1
Platform: win32 x64 10.0.19045
Electron: 22.0.0
will update, apreciate it!
