### ISSUE TITLE
Couldn't start Rotki 

### ISSUE THREAD

**Issue by CJentzsch** [rotki/rotki#7379]
## Problem Definition

Couldn't start Rotki on Mac (M1).
rotki-darwin_arm64-v1.31.3.dmg

## Logs

[rotki-core] [rotki-core] Failed to start rotki backend:
Traceback (most recent call last):
  File "rotkehlchen/__main__.py", line 17, in main
  File "rotkehlchen/server.py", line 32, in __init__
  File "rotkehlchen/rotkehlchen.py", line 155, in __init__
  File "rotkehlchen/globaldb/handler.py", line 220, in __new__
  File "rotkehlchen/globaldb/handler.py", line 185, in _initialize_global_db_directory
  File "rotkehlchen/globaldb/handler.py", line 150, in initialize_globaldb
  File "rotkehlchen/globaldb/upgrades/manager.py", line 65, in maybe_upgrade_globaldb
ValueError: Your account was last opened by a very old version of rotki and its globaldb version is 1. To be able to use it you will need to first use a previous version of rotki and then use this one. Refer to the documentation for more information. https://rotki.readthedocs.io/en/latest/usage_guide.html#upgrading-rotki-after-a-very-long-time

### System Description

Operating system: MacOS Sonoma 14.2.1
Rotki version: v1.31.3

**Comment by LefterisJP** [comment]
Hey @CJentzsch it seems that there is a very very old version of rotki remaining in your computer. It's best if you just delete the rotki directory and restart.

Or you can try what is mentioned in that link in the traceback but if it's that old it does not make sense I think. Just delete the rotki data directory and run it again.

The rotki directory in  Macos is: `~/Library/Application Support/rotki/data`

If this does not solve your problem feel free to reopen the issue.

For such quick questions it's probably best to join the discord: https://discord.rotki.com/

**Comment by CJentzsch** [comment]
That was quick :-)
