### ISSUE TITLE
500 Server Error on Fiat balance query

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#758]
## Problem Definition

This problem happened once when I tested an old account in an OSX machine with v1.2.0 candidate binary. **Once restarted the problem goes away** so that's an easy fix for the user side.

Think why this assertion can happen and handle it properly so that this error does not occur.

```
01/03/2020 18:26:56 CET -- ERROR:rotkehlchen.api.server:Exception on /api/1/balances/fiat [GET]
Traceback (most recent call last):
  File "flask/app.py", line 1949, in full_dispatch_request
  File "flask/app.py", line 1935, in dispatch_request
  File "flask_restful/__init__.py", line 458, in wrapper
  File "flask/views.py", line 89, in view
  File "flask_restful/__init__.py", line 573, in dispatch_request
  File "rotkehlchen/api/v1/resources.py", line 254, in get
  File "rotkehlchen/api/rest.py", line 101, in wrapper
  File "rotkehlchen/api/rest.py", line 582, in query_fiat_balances
  File "rotkehlchen/rotkehlchen.py", line 466, in query_fiat_balances
  File "rotkehlchen/inquirer.py", line 287, in query_fiat_pair
  File "rotkehlchen/inquirer.py", line 220, in _save_forex_rate
AssertionError: Cached value should not already exist
```

**Comment by LefterisJP** [comment]
Happened again in OSX:

```
18/03/2020 18:51:53 CET -- INFO:rotkehlchen.api.server.pywsgi:127.0.0.1 - - [2020-03-18 18:51:53] "GET /api/1/tasks/1 HTTP/1.1" 200 632 0.003678
18/03/2020 18:51:55 CET -- ERROR:rotkehlchen.api.server:Exception on /api/1/balances/fiat [GET]
Traceback (most recent call last):
  File "site-packages/flask/app.py", line 1949, in full_dispatch_request
  File "site-packages/flask/app.py", line 1935, in dispatch_request
  File "site-packages/flask_restful/__init__.py", line 458, in wrapper
  File "site-packages/flask/views.py", line 89, in view
  File "site-packages/flask_restful/__init__.py", line 573, in dispatch_request
  File "rotkehlchen/api/v1/resources.py", line 305, in get
  File "rotkehlchen/api/rest.py", line 101, in wrapper
  File "rotkehlchen/api/rest.py", line 582, in query_fiat_balances
  File "rotkehlchen/rotkehlchen.py", line 466, in query_fiat_balances
  File "rotkehlchen/inquirer.py", line 287, in query_fiat_pair
  File "rotkehlchen/inquirer.py", line 220, in _save_forex_rate
AssertionError: Cached value should not already exist
18/03/2020 18:51:55 CET -- INFO:rotkehlchen.api.server.pywsgi:127.0.0.1 - - [2020-03-18 18:51:55] "GET /api/1/balances/fiat HTTP/1.1" 500 216 3.224050
18/03/2020 18:51:55 CET -- DEBUG:rotkehlchen.api.rest:Request successful response={"result": {"Test": {"name": "Test", "description": "Test tag", "background_color": "45FC00", "foreground_color": "FFFFFF"}}, "message": ""}, status_code=200
```

**Comment by LefterisJP** [comment]
Nobody else has seen it. So closing this.
