### ISSUE TITLE
Handle SSLError when connecting to remotes

### ISSUE THREAD

**Issue by LefterisJP** [rotki/rotki#889]
## Abstract

Binance has been having some problems lately and when connecting to it we get a weird SSL error which seems to not be handled gracefully by Rotki

```
16/04/2020 09:49:09 CEST -- ERROR:rotkehlchen.api.server:Exception on /api/1/balances/ [GET]
Traceback (most recent call last):
  File "/home/lefteris/.virtualenvs/rotkipy37/lib/python3.7/site-packages/urllib3/connectionpool.py", line 600, in urlopen
    chunked=chunked)
  File "/home/lefteris/.virtualenvs/rotkipy37/lib/python3.7/site-packages/urllib3/connectionpool.py", line 343, in _make_request
    self._validate_conn(conn)
  File "/home/lefteris/.virtualenvs/rotkipy37/lib/python3.7/site-packages/urllib3/connectionpool.py", line 839, in _validate_conn
    conn.connect()
  File "/home/lefteris/.virtualenvs/rotkipy37/lib/python3.7/site-packages/urllib3/connection.py", line 344, in connect
    ssl_context=context)
  File "/home/lefteris/.virtualenvs/rotkipy37/lib/python3.7/site-packages/urllib3/util/ssl_.py", line 345, in ssl_wrap_socket
    return context.wrap_socket(sock, server_hostname=server_hostname)
  File "/home/lefteris/.virtualenvs/rotkipy37/lib/python3.7/site-packages/gevent/_ssl3.py", line 69, in wrap_socket
    _session=session)
  File "/home/lefteris/.virtualenvs/rotkipy37/lib/python3.7/site-packages/gevent/_ssl3.py", line 275, in __init__
    raise x
  File "/home/lefteris/.virtualenvs/rotkipy37/lib/python3.7/site-packages/gevent/_ssl3.py", line 271, in __init__
    self.do_handshake()
  File "/home/lefteris/.virtualenvs/rotkipy37/lib/python3.7/site-packages/gevent/_ssl3.py", line 617, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1076)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lefteris/.virtualenvs/rotkipy37/lib/python3.7/site-packages/requests/adapters.py", line 449, in send
    timeout=timeout
  File "/home/lefteris/.virtualenvs/rotkipy37/lib/python3.7/site-packages/urllib3/connectionpool.py", line 638, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/home/lefteris/.virtualenvs/rotkipy37/lib/python3.7/site-packages/urllib3/util/retry.py", line 399, in increment
    raise MaxRetryError(_pool, url, error or ResponseError(cause))
urllib3.exceptions.MaxRetryError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v1/exchangeInfo (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1076)')))
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/lefteris/.virtualenvs/rotkipy37/lib/python3.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/lefteris/.virtualenvs/rotkipy37/lib/python3.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/lefteris/.virtualenvs/rotkipy37/lib/python3.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/lefteris/.virtualenvs/rotkipy37/lib/python3.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/lefteris/.virtualenvs/rotkipy37/lib/python3.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/lefteris/.virtualenvs/rotkipy37/lib/python3.7/site-packages/webargs/core.py", line 366, in wrapper
    return func(*args, **kwargs)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/api/v1/resources.py", line 248, in get
    ignore_cache=ignore_cache,
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/api/rest.py", line 109, in wrapper
    return f(wrappingobj, *args, **kwargs)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/api/rest.py", line 332, in query_all_balances
    response = self._query_all_balances(save_data=save_data, ignore_cache=ignore_cache)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/api/rest.py", line 314, in _query_all_balances
    ignore_cache=ignore_cache,
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/rotkehlchen.py", line 502, in query_balances
    exchange_balances, _ = exchange.query_balances(ignore_cache=ignore_cache)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/utils/interfaces.py", line 110, in wrapper
    result = f(wrappingobj, *args, **kwargs)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/utils/interfaces.py", line 69, in wrapper
    result = f(wrappingobj, *args, **kwargs)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/exchanges/binance.py", line 302, in query_balances
    self.first_connection()
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/exchanges/binance.py", line 188, in first_connection
    exchange_data = self.api_query_dict('exchangeInfo')
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/exchanges/binance.py", line 290, in api_query_dict
    result = self.api_query(method, options)
  File "/home/lefteris/w/rotkehlchen/rotkehlchen/exchanges/binance.py", line 247, in api_query
    response = self.session.get(request_url)
  File "/home/lefteris/.virtualenvs/rotkipy37/lib/python3.7/site-packages/requests/sessions.py", line 537, in get
    return self.request('GET', url, **kwargs)
  File "/home/lefteris/.virtualenvs/rotkipy37/lib/python3.7/site-packages/requests/sessions.py", line 524, in request
    resp = self.send(prep, **send_kwargs)
  File "/home/lefteris/.virtualenvs/rotkipy37/lib/python3.7/site-packages/requests/sessions.py", line 637, in send
    r = adapter.send(request, **kwargs)
  File "/home/lefteris/.virtualenvs/rotkipy37/lib/python3.7/site-packages/requests/adapters.py", line 514, in send
    raise SSLError(e, request=request)
requests.exceptions.SSLError: HTTPSConnectionPool(host='api.binance.com', port=443): Max retries exceeded with url: /api/v1/exchangeInfo (Caused by SSLError(SSLError(1, '[SSL: TLSV1_ALERT_INTERNAL_ERROR] tlsv1 alert internal error (_ssl.c:1076)')))
```
## Task

Handle it gracefully :)

As seen here we can either ignore SSL verification for requests: https://stackoverflow.com/questions/10667960/python-requests-throwing-sslerror

which seems bad

Or catch `requests.exceptions.SSLError` for every requests.request() and turn it into a rotki RemoteError.

**Comment by LefterisJP** [comment]
We now catch `requests.exceptions.RequestException` which is the parent class of most exceptions in requests, including SSLError so this issue should be solved.
